---Generated by lokiagent's json converter---
Player = GetPlayer()
UseDBToRepair(true)
SetQuestRepairAt(35)
UseDBToSell(false)
SetQuestSellAt(2)


Food = {
    {level = 1, name = "Tough Hunk of Bread"},
    {level = 5, name = "Freshly Baked Bread"},
    {level = 15, name = "Moist Cornbread"},
    {level = 25, name = "Mulgore Spice Bread"},
    {level = 35, name = "Soft Banana Bread"},
    {level = 45, name = "Homemade Cherry Pie"}
}
Drink = {
    {level = 1, name = "Refreshing Spring Water"},
    {level = 5, name = "Ice Cold Milk"},
    {level = 15, name = "Melon Juice"},
    {level = 25, name = "Sweet Nectar"},
    {level = 35, name = "Moonberry Juice"},
    {level = 45, name = "Morning Glory Dew"}
}
Vendors = {
    -- Stranglethorn Vale (1434)
    {name = "Uthok", ID = 1149, friendlyAlliance = false, friendlyHorde = true, location = 1434},
    {name = "Nixxrax Fillamug", ID = 2832, friendlyAlliance = true, friendlyHorde = true, location = 1434},
    -- Ashenvale (1440)
    {name = "Maliynn", ID = 3961, friendlyAlliance = true, friendlyHorde = false, location = 1440},
    {name = "Innkeeper Sikewa", ID = 12196, friendlyAlliance = false, friendlyHorde = true, location = 1440},
    -- The Hinterlands (1425)
    {name = "Innkeeper Adegwa", ID = 8118, friendlyAlliance = false, friendlyHorde = true, location = 1425},
    -- Azshara (1447)
    {name = "Kurll", ID = 3621, friendlyAlliance = true, friendlyHorde = false, location = 1447},
    -- Feralas (1444)
    {name = "Mardrack Greenwell", ID = 7941, friendlyAlliance = false, friendlyHorde = true, location = 1444},
    {name = "Loorana", ID = 8143, friendlyAlliance = true, friendlyHorde = false, location = 1444},
    -- Desolace (1443)
    {name = "Janet Hommers", ID = 8150, friendlyAlliance = true, friendlyHorde = true, location = 1443},
    -- The Barrens (1413)
    {name = "Innkeeper Boorand Plainswind", ID = 3934, friendlyAlliance = false, friendlyHorde = true, location = 1413},
    -- Hillsbrad Foothills (1424)
    {name = "Innkeeper Shay", ID = 2388, friendlyAlliance = false, friendlyHorde = true, location = 1424},
    -- Silithus (1451)
    {name = "Calandrath", ID = 15174, friendlyAlliance = true, friendlyHorde = true, location = 1451},
    -- Badlands (1418)
    {name = "Innkeeper Shul'kar", ID = 9356, friendlyAlliance = false, friendlyHorde = true, location = 1418},
    -- Dustwallow Marsh (1445)
    {name = "Innkeeper Janene", ID = 6272, friendlyAlliance = true, friendlyHorde = false, location = 1445},
    {name = "Innkeeper Shay", ID = 2388, friendlyAlliance = false, friendlyHorde = true, location = 1445},
    -- Swamp of Sorrows (1435)
    {name = "Thultash", ID = 982, friendlyAlliance = true, friendlyHorde = false, location = 1435},
    -- Felwood (1448)
    {name = "Innkeeper Shyria", ID = 11116, friendlyAlliance = true, friendlyHorde = false, location = 1448},
    -- Winterspring (1452)
    {name = "Himmik", ID = 11187, friendlyAlliance = true, friendlyHorde = true, location = 1452},
    -- Duskwood (1431)
    {name = "Innkeeper Trelayne", ID = 6791, friendlyAlliance = true, friendlyHorde = false, location = 1431},
    -- Thousand Needles (1441)
    {name = "Laer Stepperunner", ID = 3689, friendlyAlliance = false, friendlyHorde = true, location = 1441},
    -- Eastern Plaguelands (1423)
    {name = "Innkeeper Bates", ID = 16256, friendlyAlliance = true, friendlyHorde = false, location = 1423},
    -- Arathi Highlands (1417)
    {name = "Innkeeper Kimlya", ID = 9501, friendlyAlliance = true, friendlyHorde = false, location = 1417},
    -- Wetlands (1437)
    {name = "Innkeeper Helbrek", ID = 14624, friendlyAlliance = true, friendlyHorde = false, location = 1437},
    -- Western Plaguelands (1422)
    {name = "Innkeeper Lyshaerya", ID = 12959, friendlyAlliance = true, friendlyHorde = false, location = 1422},
    -- Un'Goro Crater (1449)
    {name = "Innkeeper Karakul", ID = 11118, friendlyAlliance = true, friendlyHorde = true, location = 1449},
    -- Stonetalon Mountains (1442)
    {name = "Innkeeper Jayka", ID = 7731, friendlyAlliance = false, friendlyHorde = true, location = 1442},
    -- Searing Gorge (1427)
    {name = "Innkeeper Grilka", ID = 12944, friendlyAlliance = false, friendlyHorde = true, location = 1427},
    -- Tanaris (1446)
    {name = "Innkeeper Fizzgrimble", ID = 7733, friendlyAlliance = true, friendlyHorde = false, location = 1446},
    {name = "Innkeeper Shul'kar", ID = 9356, friendlyAlliance = false, friendlyHorde = true, location = 1446},
    -- Blasted Lands (1419)
    {name = "Bernie Heisten", ID = 3546, friendlyAlliance = true, friendlyHorde = true, location = 1419},
    -- Burning Steppes (1428)
    {name = "Gabrielle Chase", ID = 3298, friendlyAlliance = true, friendlyHorde = false, location = 1428},
    -- Silverpine Forest (1421)
    {name = "Innkeeper Bates", ID = 16256, friendlyAlliance = false, friendlyHorde = true, location = 1421},
    -- Westfall (1436)
    {name = "Innkeeper Heather", ID = 8931, friendlyAlliance = true, friendlyHorde = false, location = 1436},
    -- Moonglade (1450)
    {name = "Dargon", ID = 12019, friendlyAlliance = true, friendlyHorde = true, location = 1450},
    {name = "My'lanna", ID = 12026, friendlyAlliance = true, friendlyHorde = true, location = 1450},
    -- Redridge Mountains (1433)
    {name = "Bartender Wental", ID = 5620, friendlyAlliance = false, friendlyHorde = true, location = 1433},
    -- Darkshore (1439)
    {name = "Tiyani", ID = 4195, friendlyAlliance = true, friendlyHorde = false, location = 1439},
    -- Loch Modan (1432)
    {name = "Innkeeper Hearthstove", ID = 6734, friendlyAlliance = true, friendlyHorde = false, location = 1432},
    -- Elwynn Forest (1429)
    {name = "Innkeeper Farley", ID = 295, friendlyAlliance = true, friendlyHorde = false, location = 1429},
    -- Tirisfal Glades (1420)
    {name = "Innkeeper Renee", ID = 5688, friendlyAlliance = false, friendlyHorde = true, location = 1420},
    -- Dun Morogh (1426)
    {name = "Kazan Mogosh", ID = 1237, friendlyAlliance = true, friendlyHorde = false, location = 1426},
    -- Mulgore (1412)
    {name = "Innkeeper Kauth", ID = 6746, friendlyAlliance = false, friendlyHorde = true, location = 1412},
    -- Teldrassil (1438)
    {name = "Dellylah", ID = 6091, friendlyAlliance = true, friendlyHorde = false, location = 1438},
    -- Durotar (1411)
    {name = "Innkeeper Grosk", ID = 6928, friendlyAlliance = false, friendlyHorde = true, location = 1411},
}
function SetVendor()
    local zone = GetZoneID()
    Log(zone)
    Log(Player:IsAlliance())
    local faction -- Declare once here
    if Player:IsAlliance() == true then
        faction = "Alliance"
        Log("For the Alliance!")
    else
        faction = "Horde"
        Log("For the Horde!")
    end
    Log("Faction:" .. faction)
    local playerPos = UnitPosToFloatArray(GetPlayer())
    local bestVendor = nil

    -- Try to find a vendor in the same zone and for the player's faction
    for _, vendor in ipairs(Vendors) do
        if vendor.location == zone then
            if (faction == "Alliance" and vendor.friendlyAlliance) or (faction == "Horde" and vendor.friendlyHorde) then
                Vendor = vendor
                print("Selected Vendor: " .. Vendor.name)
                return
            end
        end
    end

    -- If not found, find the closest vendor for the player's faction
    local minDist = math.huge
    for _, vendor in ipairs(Vendors) do
        if (faction == "Alliance" and vendor.friendlyAlliance) or (faction == "Horde" and vendor.friendlyHorde) then
            local vendorPos = GetNPCPostionFromDB(vendor.ID)
            if vendorPos and playerPos then
                local dist = DistanceBetweenPoints(playerPos, vendorPos)
                if dist < minDist then
                    minDist = dist
                    bestVendor = vendor
                end
            end
        end
    end

    if bestVendor then
        Vendor = bestVendor
        print("Selected closest Vendor: " .. Vendor.name)
    else
        print("No suitable vendor found for your faction.")
        Vendor = nil
    end
    Log("This isn't working!")
end
function SetFoodAndDrink()
    if Player.Class == "Warrior" or Player.Class == "Rogue" then
        Drink = nil
    else
        local bestDrink = Drink[1]
        for i = 1, #Drink do
            if Drink[i].level <= Player.Level and Drink[i].level > bestDrink.level then
                bestDrink = Drink[i]
            end
        end
        SelectedDrink = bestDrink
    end
    for i = 1, #Food do
        if Food[i].level <= Player.Level then
            SelectedFood = Food[i]
        end
    end
    if Drink == nil then
        print("No suitable drink found for your class.")
    else
        print("Selected Drink: " .. SelectedDrink.name)
        SetDrink(SelectedDrink.name, 40)
    end
    if SelectedFood then
        print("Selected Food: " .. SelectedFood.name)
        SetFood(SelectedFood.name, 40)
    else
        print("No suitable food found for your level.")
    end
end
function Override()
    if Drink ~= nil and SelectedDrink ~= nil then
        if ItemCount(SelectedDrink.name) < 5 then
            return false
        end
    end
    if SelectedFood ~= nil then
        if ItemCount(SelectedFood.name) < 5 then
            return false
        end
    end
    return true
end
function SellAtVendor()
    if not Vendor then
        print("Error: No vendor selected.")
        return
    end
    local pos = GetNPCPostionFromDB(Vendor.ID)
    if pos then
        QuestGoToPoint(pos[0], pos[1], pos[2], false, true)
        local unit = FindUnitByName(Vendor.name)
        if unit then
            FindMeshPathToUnit(unit)
            InteractWithUnit(unit)
            SleepPlugin(3000)
        else
            print("Error: Vendor " .. Vendor.name .. " not found.")
        end
    else
        print("Error: Could not get position for vendor " .. Vendor.name)
    end
end

SetFoodAndDrink()
--Grind and Gather goes here--
SetVendor()
SellAtVendor()

local Waypoints = {
    {-923.8457,-4857.555,13.8701706},
    {-952.3998,-4852.29541,13.4849339},
    {-980.2001,-4843.1665,13.4669161},
    {-1009.27838,-4837.74561,13.0059805},
    {-1028.8103,-4814.007,13.8703165},
    {-1041.5658,-4790.62158,15.5203934},
    {-1012.09674,-4766.59,12.7794294},
    {-983.22,-4760.38525,13.3119907},
    {-934.7146,-4756.22559,18.8176384},
    {-911.1145,-4742.49951,22.16362},
    {-885.5023,-4716.536,25.89868},
    {-858.3545,-4695.24854,29.7482376},
    {-819.5962,-4682.21045,33.92476},
    {-793.031433,-4696.745,33.64266},
    {-774.0286,-4720.6543,31.42529},
    {-789.053345,-4771.511,30.1294174},
    {-828.1507,-4816.95166,21.5996933}
}

local TargetNames = {
    "Clattering Scorpid", "Dire Mottled Boar"
}

SetFoodAndDrink()
GrindAndGatherPath(TableToStringList(TargetNames), TableToVecList(Waypoints), 40, false, "Override")
SetVendor()
SellAtVendor()
