---Generated by lokiagent's json converter---
Player = GetPlayer()
UseDBToRepair(false)
SetQuestRepairAt(30)
UseDBToSell(false)
SetQuestSellAt(2)
BlackListPoint(-7757.058, -1446.9718, 182.243134)
BlackListPoint(-7910.37744, -1339.364, 127.845451)
BlackListPoint(-7969.69141, -1245.99243, 134.017853)
BlackListPoint(-7951.9585, -1295.03577, 143.335571)
BlackListPoint(-7941.97, -1312.17407, 142.556442)
BlackListPoint(-7945.81152, -1307.14539, 193.113968)
BlackListPoint(-7956.923, -1281.25574, 132.548767)
BlackListPoint(-7960.096, -1269.72717, 133.519333)
BlackListPoint(-7963.087, -1257.64832, 133.117615)
BlackListPoint(-7934.96436, -1320.27026, 142.171524)
BlackListPoint(-7907.06445, -1329.63037, 134.924667)
BlackListPoint(-7858.40137, -2079.413, 131.168884)
BlackListPoint(-7753.108, -2331.815, 135.475586)
BlackListPoint(-8259.676, -1196.73572, 132.176331)
BlackListPoint(-7633.76, -1421.309, 130.748215)
BlackListPoint(-7655.654, -1369.82336, 133.488785)
BlackListPoint(-7680.86, -1376.47607, 134.942215)
BlackListPoint(-7706.35059, -1385.54871, 133.718277)
BlackListPoint(-7732.364, -1378.87219, 134.091476)
BlackListPoint(-7953.55225, -895.2506, 130.501053)
BlackListPoint(-7627.75732, -3007.74316, 136.216187)
BlackListPoint(-7609.39648, -3031.36157, 132.5355)
BlackListPoint(-8188.24365, -703.5019, 132.967438)
BlackListPoint(-7614.44727, -3027.15845, 147.8071)
BlackListPoint(-7655.774, -2290.38525, 133.694061)
BlackListPoint(-7638.631, -2305.507, 139.873)
BlackListPoint(-7661.31445, -2306.406, 140.389389)
BlackListPoint(-7765.753, -1637.29871, 131.258057)
BlackListPoint(-8183.0957, -1928.92993, 141.5526)
BlackListPoint(-7715.472, -2989.02686, 133.505112)
BlackListPoint(-7726.345, -2361.27173, 138.705948)
BlackListPoint(-7698.264, -2349.39, 147.010086)
BlackListPoint(-7821.929, -2936.43115, 130.798676)
BlackListPoint(-8259.392, -1196.71863, 143.03299)
BlackListPoint(-8211.575, -2441.00464, 138.34761)
BlackListPoint(-8113.411, -2827.31982, 134.042358)
BlackListPoint(-7663.70361, -718.1517, 184.378036)
BlackListPoint(-7664.248, -724.4855, 182.981842)
BlackListPoint(-7666.95947, -732.3492, 182.966278)
BlackListPoint(-7634.80664, -717.9648, 183.7222)
BlackListPoint(-7631.281, -721.223145, 183.107224)
BlackListPoint(-7628.63672, -726.5361, 182.2296)
BlackListPoint(-7634.146, -706.7225, 184.075424)
BlackListPoint(-7629.828, -703.500061, 183.429031)
BlackListPoint(-7625.13135, -702.1508, 182.88591)
BlackListPoint(-7619.374, -705.7447, 182.621628)
BlackListPoint(-7657.739, -701.1558, 181.485428)
BlackListPoint(-7652.45752, -697.756531, 179.487228)
BlackListPoint(-7649.59375, -692.442749, 180.412521)
BlackListPoint(-7646.398, -688.2317, 181.063217)
BlackListPoint(-7642.85352, -684.5513, 181.109146)
BlackListPoint(-7635.9043, -684.171143, 180.365082)
BlackListPoint(-8088.93, -1527.40564, 136.105057)
BlackListPoint(-8089.795, -1532.75757, 133.300323)
BlackListPoint(-8104.023, -1533.62524, 133.6132)
BlackListPoint(-8110.232, -1520.172, 133.332214)
BlackListPoint(-8100.55225, -1513.87732, 133.182922)
BlackListPoint(-8089.608, -1517.09216, 133.446442)
BlackListPoint(-8088.79443, -1523.39856, 133.388885)
BlackListPoint(-7914.646, -938.58374, 132.44397)
BlackListPoint(-7921.69141, -941.7933, 132.3123)
BlackListPoint(-7927.6084, -947.217834, 130.936066)
BlackListPoint(-7928.54639, -954.310364, 131.399033)
BlackListPoint(-7927.16357, -961.615662, 130.1149)
BlackListPoint(-8162.48145, -1038.69238, 134.187042)
BlackListPoint(-8163.4043, -1049.09363, 136.148087)
BlackListPoint(-7870.167, -901.477051, 133.502792)
BlackListPoint(-7865.796, -904.0379, 128.9775)
BlackListPoint(-7859.007, -904.0017, 127.853561)
BlackListPoint(-7853.343, -903.57196, 127.898941)
BlackListPoint(-7874.067, -906.695862, 130.694656)
BlackListPoint(-7877.63135, -909.572632, 130.68689)
BlackListPoint(-7880.989, -912.2826, 131.22287)
BlackListPoint(-7884.53027, -916.0575, 130.576462)
BlackListPoint(-7888.964, -920.7835, 130.613632)
BlackListPoint(-7892.38428, -924.870056, 130.650818)
BlackListPoint(-7895.856, -929.5516, 130.1905)
BlackListPoint(-7898.989, -932.364441, 130.4045)
BlackListPoint(-7902.94434, -934.9788, 130.7776)
BlackListPoint(-7907.396, -936.804749, 131.0523)
BlackListPoint(-7912.08252, -938.2289, 131.776825)
BlackListPoint(-7917.288, -940.458862, 132.131287)
BlackListPoint(-7925.63965, -945.140137, 131.084152)
BlackListPoint(-7927.59375, -952.3068, 130.112549)


Food = {
    {level = 1, name = "Tough Hunk of Bread"},
    {level = 5, name = "Freshly Baked Bread"},
    {level = 15, name = "Moist Cornbread"},
    {level = 25, name = "Mulgore Spice Bread"},
    {level = 35, name = "Soft Banana Bread"},
    {level = 45, name = "Homemade Cherry Pie"}
}
Drink = {
    {level = 1, name = "Refreshing Spring Water"},
    {level = 5, name = "Ice Cold Milk"},
    {level = 15, name = "Melon Juice"},
    {level = 25, name = "Sweet Nectar"},
    {level = 35, name = "Moonberry Juice"},
    {level = 45, name = "Morning Glory Dew"}
}
Vendors = {
    -- Stranglethorn Vale (1434)
    {name = "Uthok", ID = 1149, friendlyAlliance = false, friendlyHorde = true, location = 1434},
    {name = "Nixxrax Fillamug", ID = 2832, friendlyAlliance = true, friendlyHorde = true, location = 1434},
    -- Ashenvale (1440)
    {name = "Maliynn", ID = 3961, friendlyAlliance = true, friendlyHorde = false, location = 1440},
    {name = "Innkeeper Sikewa", ID = 12196, friendlyAlliance = false, friendlyHorde = true, location = 1440},
    -- The Hinterlands (1425)
    {name = "Innkeeper Adegwa", ID = 8118, friendlyAlliance = false, friendlyHorde = true, location = 1425},
    -- Azshara (1447)
    {name = "Kurll", ID = 3621, friendlyAlliance = true, friendlyHorde = false, location = 1447},
    -- Feralas (1444)
    {name = "Mardrack Greenwell", ID = 7941, friendlyAlliance = false, friendlyHorde = true, location = 1444},
    {name = "Loorana", ID = 8143, friendlyAlliance = true, friendlyHorde = false, location = 1444},
    -- Desolace (1443)
    {name = "Janet Hommers", ID = 8150, friendlyAlliance = true, friendlyHorde = true, location = 1443},
    -- The Barrens (1413)
    {name = "Innkeeper Boorand Plainswind", ID = 3934, friendlyAlliance = false, friendlyHorde = true, location = 1413},
    -- Hillsbrad Foothills (1424)
    {name = "Innkeeper Shay", ID = 2388, friendlyAlliance = false, friendlyHorde = true, location = 1424},
    -- Silithus (1451)
    {name = "Calandrath", ID = 15174, friendlyAlliance = true, friendlyHorde = true, location = 1451},
    -- Badlands (1418)
    {name = "Innkeeper Shul'kar", ID = 9356, friendlyAlliance = false, friendlyHorde = true, location = 1418},
    -- Dustwallow Marsh (1445)
    {name = "Innkeeper Janene", ID = 6272, friendlyAlliance = true, friendlyHorde = false, location = 1445},
    {name = "Innkeeper Shay", ID = 2388, friendlyAlliance = false, friendlyHorde = true, location = 1445},
    -- Swamp of Sorrows (1435)
    {name = "Thultash", ID = 982, friendlyAlliance = true, friendlyHorde = false, location = 1435},
    -- Felwood (1448)
    {name = "Innkeeper Shyria", ID = 11116, friendlyAlliance = true, friendlyHorde = false, location = 1448},
    -- Winterspring (1452)
    {name = "Himmik", ID = 11187, friendlyAlliance = true, friendlyHorde = true, location = 1452},
    -- Duskwood (1431)
    {name = "Innkeeper Trelayne", ID = 6791, friendlyAlliance = true, friendlyHorde = false, location = 1431},
    -- Thousand Needles (1441)
    {name = "Laer Stepperunner", ID = 3689, friendlyAlliance = false, friendlyHorde = true, location = 1441},
    -- Eastern Plaguelands (1423)
    {name = "Innkeeper Bates", ID = 16256, friendlyAlliance = true, friendlyHorde = false, location = 1423},
    -- Arathi Highlands (1417)
    {name = "Innkeeper Kimlya", ID = 9501, friendlyAlliance = true, friendlyHorde = false, location = 1417},
    -- Wetlands (1437)
    {name = "Innkeeper Helbrek", ID = 14624, friendlyAlliance = true, friendlyHorde = false, location = 1437},
    -- Western Plaguelands (1422)
    {name = "Innkeeper Lyshaerya", ID = 12959, friendlyAlliance = true, friendlyHorde = false, location = 1422},
    -- Un'Goro Crater (1449)
    {name = "Innkeeper Karakul", ID = 11118, friendlyAlliance = true, friendlyHorde = true, location = 1449},
    -- Stonetalon Mountains (1442)
    {name = "Innkeeper Jayka", ID = 7731, friendlyAlliance = false, friendlyHorde = true, location = 1442},
    -- Searing Gorge (1427)
    {name = "Innkeeper Grilka", ID = 12944, friendlyAlliance = false, friendlyHorde = true, location = 1427},
    -- Tanaris (1446)
    {name = "Innkeeper Fizzgrimble", ID = 7733, friendlyAlliance = true, friendlyHorde = false, location = 1446},
    {name = "Innkeeper Shul'kar", ID = 9356, friendlyAlliance = false, friendlyHorde = true, location = 1446},
    -- Blasted Lands (1419)
    {name = "Bernie Heisten", ID = 3546, friendlyAlliance = true, friendlyHorde = true, location = 1419},
    -- Burning Steppes (1428)
    {name = "Gabrielle Chase", ID = 3298, friendlyAlliance = true, friendlyHorde = false, location = 1428},
    -- Silverpine Forest (1421)
    {name = "Innkeeper Bates", ID = 16256, friendlyAlliance = false, friendlyHorde = true, location = 1421},
    -- Westfall (1436)
    {name = "Innkeeper Heather", ID = 8931, friendlyAlliance = true, friendlyHorde = false, location = 1436},
    -- Moonglade (1450)
    {name = "Dargon", ID = 12019, friendlyAlliance = true, friendlyHorde = true, location = 1450},
    {name = "My'lanna", ID = 12026, friendlyAlliance = true, friendlyHorde = true, location = 1450},
    -- Redridge Mountains (1433)
    {name = "Bartender Wental", ID = 5620, friendlyAlliance = false, friendlyHorde = true, location = 1433},
    -- Darkshore (1439)
    {name = "Tiyani", ID = 4195, friendlyAlliance = true, friendlyHorde = false, location = 1439},
    -- Loch Modan (1432)
    {name = "Innkeeper Hearthstove", ID = 6734, friendlyAlliance = true, friendlyHorde = false, location = 1432},
    -- Elwynn Forest (1429)
    {name = "Innkeeper Farley", ID = 295, friendlyAlliance = true, friendlyHorde = false, location = 1429},
    -- Tirisfal Glades (1420)
    {name = "Innkeeper Renee", ID = 5688, friendlyAlliance = false, friendlyHorde = true, location = 1420},
    -- Dun Morogh (1426)
    {name = "Kazan Mogosh", ID = 1237, friendlyAlliance = true, friendlyHorde = false, location = 1426},
    -- Mulgore (1412)
    {name = "Innkeeper Kauth", ID = 6746, friendlyAlliance = false, friendlyHorde = true, location = 1412},
    -- Teldrassil (1438)
    {name = "Dellylah", ID = 6091, friendlyAlliance = true, friendlyHorde = false, location = 1438},
    -- Durotar (1411)
    {name = "Innkeeper Grosk", ID = 6928, friendlyAlliance = false, friendlyHorde = true, location = 1411},
}
function SetVendor()
    local zone = GetZoneID()
    Log(zone)
    Log(Player:IsAlliance())
    local faction -- Declare once here
    if Player:IsAlliance() == true then
        faction = "Alliance"
        Log("For the Alliance!")
    else
        faction = "Horde"
        Log("For the Horde!")
    end
    Log("Faction:" .. faction)
    local playerPos = UnitPosToFloatArray(GetPlayer())
    local bestVendor = nil

    -- Try to find a vendor in the same zone and for the player's faction
    for _, vendor in ipairs(Vendors) do
        if vendor.location == zone then
            if (faction == "Alliance" and vendor.friendlyAlliance) or (faction == "Horde" and vendor.friendlyHorde) then
                Vendor = vendor
                print("Selected Vendor: " .. Vendor.name)
                return
            end
        end
    end

    -- If not found, find the closest vendor for the player's faction
    local minDist = math.huge
    for _, vendor in ipairs(Vendors) do
        if (faction == "Alliance" and vendor.friendlyAlliance) or (faction == "Horde" and vendor.friendlyHorde) then
            local vendorPos = GetNPCPostionFromDB(vendor.ID)
            if vendorPos and playerPos then
                local dist = DistanceBetweenPoints(playerPos, vendorPos)
                if dist < minDist then
                    minDist = dist
                    bestVendor = vendor
                end
            end
        end
    end

    if bestVendor then
        Vendor = bestVendor
        print("Selected closest Vendor: " .. Vendor.name)
    else
        print("No suitable vendor found for your faction.")
        Vendor = nil
    end
    Log("This isn't working!")
end
function SetFoodAndDrink()
    if Player.Class == "Warrior" or Player.Class == "Rogue" then
        Drink = nil
    else
        local bestDrink = Drink[1]
        for i = 1, #Drink do
            if Drink[i].level <= Player.Level and Drink[i].level > bestDrink.level then
                bestDrink = Drink[i]
            end
        end
        SelectedDrink = bestDrink
    end
    for i = 1, #Food do
        if Food[i].level <= Player.Level then
            SelectedFood = Food[i]
        end
    end
    if Drink == nil then
        print("No suitable drink found for your class.")
    else
        print("Selected Drink: " .. SelectedDrink.name)
        SetDrink(SelectedDrink.name, 40)
    end
    if SelectedFood then
        print("Selected Food: " .. SelectedFood.name)
        SetFood(SelectedFood.name, 40)
    else
        print("No suitable food found for your level.")
    end
end
function Override()
    if Drink ~= nil and SelectedDrink ~= nil then
        if ItemCount(SelectedDrink.name) < 5 then
            return false
        end
    end
    if SelectedFood ~= nil then
        if ItemCount(SelectedFood.name) < 5 then
            return false
        end
    end
    return true
end
function SellAtVendor()
    if not Vendor then
        print("Error: No vendor selected.")
        return
    end
    local pos = GetNPCPostionFromDB(Vendor.ID)
    if pos then
        QuestGoToPoint(pos[0], pos[1], pos[2], false, true)
        local unit = FindUnitByName(Vendor.name)
        if unit then
            FindMeshPathToUnit(unit)
            InteractWithUnit(unit)
            SleepPlugin(3000)
        else
            print("Error: Vendor " .. Vendor.name .. " not found.")
        end
    else
        print("Error: Could not get position for vendor " .. Vendor.name)
    end
end

SetFoodAndDrink()
--Grind and Gather goes here--
SetVendor()
SellAtVendor()

local Waypoints = {
    {-7687.83,-695.040161,182.1936},
    {-7934.41357,-865.6653,128.996292},
    {-7922.062,-1001.82581,133.261887},
    {-8166.17041,-1003.69421,135.230667},
    {-8402.805,-1202.86475,187.292618},
    {-8220.384,-1505.38684,142.557083},
    {-8117.01025,-1768.28662,133.0219},
    {-8213.645,-1931.07764,142.557144},
    {-8189.22852,-2111.863,143.364609},
    {-8228.483,-2546.443,135.142334},
    {-8058.18066,-2939.39136,135.260391},
    {-7760.359,-2960.23462,133.090561},
    {-7618.216,-2943.188,131.1227},
    {-7558.86475,-2568.00684,136.444092},
    {-7598.29053,-2383.17773,138.18158},
    {-7725.504,-2245.68,137.796448},
    {-7746.4917,-1997.74524,133.455444},
    {-7765.412,-1558.78064,132.4043},
    {-7775.33057,-1765.41931,133.4762},
    {-7800.783,-1907.80664,134.198883},
    {-7945.25244,-1863.48132,132.508148},
    {-8007.05469,-1342.974,134.215118},
    {-8117.477,-749.796631,134.520889},
    {-7946.02148,-858.180847,127.766571},
    {-7690.81152,-708.7457,182.353714}
}

local TargetNames = {
    "Mountain Silversage", "Rich Thorium Vein", "Small Thorium Vein", "Black Lotus", "Sungrass", "Dreamfoil", "Golden Sansam", "Mithril Deposit", "Truesilver Deposit", "Dark Iron Deposit", "Gold Vein", "Thorium Vein"
}

SetFoodAndDrink()
GrindAndGatherPath(TableToStringList(TargetNames), TableToVecList(Waypoints), 40, false, "Override")
SetVendor()
SellAtVendor()
