---Generated by lokiagent's json converter---
Player = GetPlayer()
UseDBToRepair(false)
SetQuestRepairAt(30)
UseDBToSell(false)
SetQuestSellAt(2)
BlackListPoint(463.7142, -3322.57251, 120.71122)
BlackListPoint(244.648514, -2754.89429, 116.556725)
BlackListPoint(-67.61784, -2474.40527, 139.812973)
BlackListPoint(495.537476, -3730.48145, 101.292549)
BlackListPoint(502.8586, -3780.49072, 98.45462)
BlackListPoint(501.55014, -3840.11768, 100.120148)
BlackListPoint(497.120026, -3899.51978, 101.518845)
BlackListPoint(-292.58493, -2951.808, 82.93687)
BlackListPoint(-346.399933, -2936.88184, 75.35612)
BlackListPoint(-260.108856, -2549.591, 117.293839)
BlackListPoint(-329.1367, -4205.96143, 152.009445)
BlackListPoint(-69.7203445, -4043.72119, 122.713509)
BlackListPoint(-215.161133, -4042.83154, 173.9892)
BlackListPoint(-204.498657, -3976.3313, 195.118561)
BlackListPoint(-456.8067, -2887.1377, 104.299828)
BlackListPoint(-417.839752, -2832.64551, 79.44351)
BlackListPoint(-444.070282, -2821.17725, 96.39672)
BlackListPoint(-252.940552, -2768.51147, 114.43576)
BlackListPoint(-280.2851, -4109.30762, 137.945984)
BlackListPoint(-195.66066, -4093.06177, 152.173035)
BlackListPoint(-310.3313, -2816.12354, 87.02013)
BlackListPoint(-291.365936, -2811.297, 106.923851)
BlackListPoint(-300.8501, -2813.59277, 94.8322449)
BlackListPoint(-275.168976, -2840.738, 103.063141)
BlackListPoint(-281.110046, -2846.377, 95.5856552)
BlackListPoint(-286.7359, -2853.17065, 86.46719)
BlackListPoint(-350.308319, -2974.64819, 100.231857)
BlackListPoint(-347.621063, -2965.10278, 90.68522)
BlackListPoint(-343.495453, -2957.01831, 82.83969)
BlackListPoint(-385.00116, -2972.98145, 98.89494)
BlackListPoint(-384.737579, -2962.41382, 93.8362045)
BlackListPoint(-386.732635, -2954.86646, 82.3024445)
BlackListPoint(-459.654816, -2857.95337, 97.95227)
BlackListPoint(-453.504852, -2862.19727, 87.8414459)
BlackListPoint(-449.203125, -2823.03369, 96.37057)
BlackListPoint(-438.918884, -2822.10864, 87.25469)


Food = {
    {level = 1, name = "Tough Hunk of Bread"},
    {level = 5, name = "Freshly Baked Bread"},
    {level = 15, name = "Moist Cornbread"},
    {level = 25, name = "Mulgore Spice Bread"},
    {level = 35, name = "Soft Banana Bread"},
    {level = 45, name = "Homemade Cherry Pie"}
}
Drink = {
    {level = 1, name = "Refreshing Spring Water"},
    {level = 5, name = "Ice Cold Milk"},
    {level = 15, name = "Melon Juice"},
    {level = 25, name = "Sweet Nectar"},
    {level = 35, name = "Moonberry Juice"},
    {level = 45, name = "Morning Glory Dew"}
}
Vendors = {
    -- Stranglethorn Vale (1434)
    {name = "Uthok", ID = 1149, friendlyAlliance = false, friendlyHorde = true, location = 1434},
    {name = "Nixxrax Fillamug", ID = 2832, friendlyAlliance = true, friendlyHorde = true, location = 1434},
    -- Ashenvale (1440)
    {name = "Maliynn", ID = 3961, friendlyAlliance = true, friendlyHorde = false, location = 1440},
    {name = "Innkeeper Sikewa", ID = 12196, friendlyAlliance = false, friendlyHorde = true, location = 1440},
    -- The Hinterlands (1425)
    {name = "Innkeeper Adegwa", ID = 8118, friendlyAlliance = false, friendlyHorde = true, location = 1425},
    -- Azshara (1447)
    {name = "Kurll", ID = 3621, friendlyAlliance = true, friendlyHorde = false, location = 1447},
    -- Feralas (1444)
    {name = "Mardrack Greenwell", ID = 7941, friendlyAlliance = false, friendlyHorde = true, location = 1444},
    {name = "Loorana", ID = 8143, friendlyAlliance = true, friendlyHorde = false, location = 1444},
    -- Desolace (1443)
    {name = "Janet Hommers", ID = 8150, friendlyAlliance = true, friendlyHorde = true, location = 1443},
    -- The Barrens (1413)
    {name = "Innkeeper Boorand Plainswind", ID = 3934, friendlyAlliance = false, friendlyHorde = true, location = 1413},
    -- Hillsbrad Foothills (1424)
    {name = "Innkeeper Shay", ID = 2388, friendlyAlliance = false, friendlyHorde = true, location = 1424},
    -- Silithus (1451)
    {name = "Calandrath", ID = 15174, friendlyAlliance = true, friendlyHorde = true, location = 1451},
    -- Badlands (1418)
    {name = "Innkeeper Shul'kar", ID = 9356, friendlyAlliance = false, friendlyHorde = true, location = 1418},
    -- Dustwallow Marsh (1445)
    {name = "Innkeeper Janene", ID = 6272, friendlyAlliance = true, friendlyHorde = false, location = 1445},
    {name = "Innkeeper Shay", ID = 2388, friendlyAlliance = false, friendlyHorde = true, location = 1445},
    -- Swamp of Sorrows (1435)
    {name = "Thultash", ID = 982, friendlyAlliance = true, friendlyHorde = false, location = 1435},
    -- Felwood (1448)
    {name = "Innkeeper Shyria", ID = 11116, friendlyAlliance = true, friendlyHorde = false, location = 1448},
    -- Winterspring (1452)
    {name = "Himmik", ID = 11187, friendlyAlliance = true, friendlyHorde = true, location = 1452},
    -- Duskwood (1431)
    {name = "Innkeeper Trelayne", ID = 6791, friendlyAlliance = true, friendlyHorde = false, location = 1431},
    -- Thousand Needles (1441)
    {name = "Laer Stepperunner", ID = 3689, friendlyAlliance = false, friendlyHorde = true, location = 1441},
    -- Eastern Plaguelands (1423)
    {name = "Innkeeper Bates", ID = 16256, friendlyAlliance = true, friendlyHorde = false, location = 1423},
    -- Arathi Highlands (1417)
    {name = "Innkeeper Kimlya", ID = 9501, friendlyAlliance = true, friendlyHorde = false, location = 1417},
    -- Wetlands (1437)
    {name = "Innkeeper Helbrek", ID = 14624, friendlyAlliance = true, friendlyHorde = false, location = 1437},
    -- Western Plaguelands (1422)
    {name = "Innkeeper Lyshaerya", ID = 12959, friendlyAlliance = true, friendlyHorde = false, location = 1422},
    -- Un'Goro Crater (1449)
    {name = "Innkeeper Karakul", ID = 11118, friendlyAlliance = true, friendlyHorde = true, location = 1449},
    -- Stonetalon Mountains (1442)
    {name = "Innkeeper Jayka", ID = 7731, friendlyAlliance = false, friendlyHorde = true, location = 1442},
    -- Searing Gorge (1427)
    {name = "Innkeeper Grilka", ID = 12944, friendlyAlliance = false, friendlyHorde = true, location = 1427},
    -- Tanaris (1446)
    {name = "Innkeeper Fizzgrimble", ID = 7733, friendlyAlliance = true, friendlyHorde = false, location = 1446},
    {name = "Innkeeper Shul'kar", ID = 9356, friendlyAlliance = false, friendlyHorde = true, location = 1446},
    -- Blasted Lands (1419)
    {name = "Bernie Heisten", ID = 3546, friendlyAlliance = true, friendlyHorde = true, location = 1419},
    -- Burning Steppes (1428)
    {name = "Gabrielle Chase", ID = 3298, friendlyAlliance = true, friendlyHorde = false, location = 1428},
    -- Silverpine Forest (1421)
    {name = "Innkeeper Bates", ID = 16256, friendlyAlliance = false, friendlyHorde = true, location = 1421},
    -- Westfall (1436)
    {name = "Innkeeper Heather", ID = 8931, friendlyAlliance = true, friendlyHorde = false, location = 1436},
    -- Moonglade (1450)
    {name = "Dargon", ID = 12019, friendlyAlliance = true, friendlyHorde = true, location = 1450},
    {name = "My'lanna", ID = 12026, friendlyAlliance = true, friendlyHorde = true, location = 1450},
    -- Redridge Mountains (1433)
    {name = "Bartender Wental", ID = 5620, friendlyAlliance = false, friendlyHorde = true, location = 1433},
    -- Darkshore (1439)
    {name = "Tiyani", ID = 4195, friendlyAlliance = true, friendlyHorde = false, location = 1439},
    -- Loch Modan (1432)
    {name = "Innkeeper Hearthstove", ID = 6734, friendlyAlliance = true, friendlyHorde = false, location = 1432},
    -- Elwynn Forest (1429)
    {name = "Innkeeper Farley", ID = 295, friendlyAlliance = true, friendlyHorde = false, location = 1429},
    -- Tirisfal Glades (1420)
    {name = "Innkeeper Renee", ID = 5688, friendlyAlliance = false, friendlyHorde = true, location = 1420},
    -- Dun Morogh (1426)
    {name = "Kazan Mogosh", ID = 1237, friendlyAlliance = true, friendlyHorde = false, location = 1426},
    -- Mulgore (1412)
    {name = "Innkeeper Kauth", ID = 6746, friendlyAlliance = false, friendlyHorde = true, location = 1412},
    -- Teldrassil (1438)
    {name = "Dellylah", ID = 6091, friendlyAlliance = true, friendlyHorde = false, location = 1438},
    -- Durotar (1411)
    {name = "Innkeeper Grosk", ID = 6928, friendlyAlliance = false, friendlyHorde = true, location = 1411},
}
function SetVendor()
    local zone = GetZoneID()
    Log(zone)
    Log(Player:IsAlliance())
    local faction -- Declare once here
    if Player:IsAlliance() == true then
        faction = "Alliance"
        Log("For the Alliance!")
    else
        faction = "Horde"
        Log("For the Horde!")
    end
    Log("Faction:" .. faction)
    local playerPos = UnitPosToFloatArray(GetPlayer())
    local bestVendor = nil

    -- Try to find a vendor in the same zone and for the player's faction
    for _, vendor in ipairs(Vendors) do
        if vendor.location == zone then
            if (faction == "Alliance" and vendor.friendlyAlliance) or (faction == "Horde" and vendor.friendlyHorde) then
                Vendor = vendor
                print("Selected Vendor: " .. Vendor.name)
                return
            end
        end
    end

    -- If not found, find the closest vendor for the player's faction
    local minDist = math.huge
    for _, vendor in ipairs(Vendors) do
        if (faction == "Alliance" and vendor.friendlyAlliance) or (faction == "Horde" and vendor.friendlyHorde) then
            local vendorPos = GetNPCPostionFromDB(vendor.ID)
            if vendorPos and playerPos then
                local dist = DistanceBetweenPoints(playerPos, vendorPos)
                if dist < minDist then
                    minDist = dist
                    bestVendor = vendor
                end
            end
        end
    end

    if bestVendor then
        Vendor = bestVendor
        print("Selected closest Vendor: " .. Vendor.name)
    else
        print("No suitable vendor found for your faction.")
        Vendor = nil
    end
    Log("This isn't working!")
end
function SetFoodAndDrink()
    if Player.Class == "Warrior" or Player.Class == "Rogue" then
        Drink = nil
    else
        local bestDrink = Drink[1]
        for i = 1, #Drink do
            if Drink[i].level <= Player.Level and Drink[i].level > bestDrink.level then
                bestDrink = Drink[i]
            end
        end
        SelectedDrink = bestDrink
    end
    for i = 1, #Food do
        if Food[i].level <= Player.Level then
            SelectedFood = Food[i]
        end
    end
    if Drink == nil then
        print("No suitable drink found for your class.")
    else
        print("Selected Drink: " .. SelectedDrink.name)
        SetDrink(SelectedDrink.name, 40)
    end
    if SelectedFood then
        print("Selected Food: " .. SelectedFood.name)
        SetFood(SelectedFood.name, 40)
    else
        print("No suitable food found for your level.")
    end
end
function Override()
    if Drink ~= nil and SelectedDrink ~= nil then
        if ItemCount(SelectedDrink.name) < 5 then
            return false
        end
    end
    if SelectedFood ~= nil then
        if ItemCount(SelectedFood.name) < 5 then
            return false
        end
    end
    return true
end
function SellAtVendor()
    if not Vendor then
        print("Error: No vendor selected.")
        return
    end
    local pos = GetNPCPostionFromDB(Vendor.ID)
    if pos then
        QuestGoToPoint(pos[0], pos[1], pos[2], false, true)
        local unit = FindUnitByName(Vendor.name)
        if unit then
            FindMeshPathToUnit(unit)
            InteractWithUnit(unit)
            SleepPlugin(3000)
        else
            print("Error: Vendor " .. Vendor.name .. " not found.")
        end
    else
        print("Error: Could not get position for vendor " .. Vendor.name)
    end
end

SetFoodAndDrink()
--Grind and Gather goes here--
SetVendor()
SellAtVendor()

local Waypoints = {
    {-109.155159,-4325.557,135.46167},
    {187.588074,-4585.534,119.80233},
    {75.47401,-4197.34375,126.690796},
    {402.154663,-4071.374,116.848557},
    {478.592316,-3788.04517,119.77787},
    {456.653473,-3364.83667,120.14901},
    {327.134979,-3237.833,117.288071},
    {365.098328,-2871.847,118.82869},
    {114.338722,-2667.89087,113.061974},
    {-23.44702,-2492.766,120.3813},
    {-243.959747,-2571.34668,118.266251},
    {-129.780563,-2775.50952,118.762329},
    {-170.234,-2952.53638,115.568314},
    {-374.1787,-2796.44,76.9181442},
    {-408.846924,-2941.68457,83.08675},
    {-164.846985,-2955.12817,115.760513},
    {-347.082825,-3315.84985,133.129227},
    {-192.986023,-3525.44824,135.414688},
    {101.063469,-3755.7334,127.153877},
    {-34.809063,-3992.33179,130.598083},
    {-193.481354,-4198.334,120.043304},
    {-70.7239,-4364.038,129.599854}
}

local TargetNames = {
    "Truesilver Deposit", "Khadgar's Whisker", "Goldthorn", "Golden Sansam", "Mithril Deposit", "Liferoot", "Iron Deposit", "Sungrass", "Gold Vein", "Purple Lotus", "Small Thorium Vein", "Fadeleaf"
}

SetFoodAndDrink()
GrindAndGatherPath(TableToStringList(TargetNames), TableToVecList(Waypoints), 40, false, "Override")
SetVendor()
SellAtVendor()
