---Generated by lokiagent's json converter---
Player = GetPlayer()
UseDBToRepair(false)
SetQuestRepairAt(30)
UseDBToSell(false)
SetQuestSellAt(2)


Food = {
    {level = 1, name = "Tough Hunk of Bread"},
    {level = 5, name = "Freshly Baked Bread"},
    {level = 15, name = "Moist Cornbread"},
    {level = 25, name = "Mulgore Spice Bread"},
    {level = 35, name = "Soft Banana Bread"},
    {level = 45, name = "Homemade Cherry Pie"}
}
Drink = {
    {level = 1, name = "Refreshing Spring Water"},
    {level = 5, name = "Ice Cold Milk"},
    {level = 15, name = "Melon Juice"},
    {level = 25, name = "Sweet Nectar"},
    {level = 35, name = "Moonberry Juice"},
    {level = 45, name = "Morning Glory Dew"}
}
Vendors = {
    -- Stranglethorn Vale (1434)
    {name = "Uthok", ID = 1149, friendlyAlliance = false, friendlyHorde = true, location = 1434},
    {name = "Nixxrax Fillamug", ID = 2832, friendlyAlliance = true, friendlyHorde = true, location = 1434},
    -- Ashenvale (1440)
    {name = "Maliynn", ID = 3961, friendlyAlliance = true, friendlyHorde = false, location = 1440},
    {name = "Innkeeper Sikewa", ID = 12196, friendlyAlliance = false, friendlyHorde = true, location = 1440},
    -- The Hinterlands (1425)
    {name = "Innkeeper Adegwa", ID = 8118, friendlyAlliance = false, friendlyHorde = true, location = 1425},
    -- Azshara (1447)
    {name = "Kurll", ID = 3621, friendlyAlliance = true, friendlyHorde = false, location = 1447},
    -- Feralas (1444)
    {name = "Mardrack Greenwell", ID = 7941, friendlyAlliance = false, friendlyHorde = true, location = 1444},
    {name = "Loorana", ID = 8143, friendlyAlliance = true, friendlyHorde = false, location = 1444},
    -- Desolace (1443)
    {name = "Janet Hommers", ID = 8150, friendlyAlliance = true, friendlyHorde = true, location = 1443},
    -- The Barrens (1413)
    {name = "Innkeeper Boorand Plainswind", ID = 3934, friendlyAlliance = false, friendlyHorde = true, location = 1413},
    -- Hillsbrad Foothills (1424)
    {name = "Innkeeper Shay", ID = 2388, friendlyAlliance = false, friendlyHorde = true, location = 1424},
    -- Silithus (1451)
    {name = "Calandrath", ID = 15174, friendlyAlliance = true, friendlyHorde = true, location = 1451},
    -- Badlands (1418)
    {name = "Innkeeper Shul'kar", ID = 9356, friendlyAlliance = false, friendlyHorde = true, location = 1418},
    -- Dustwallow Marsh (1445)
    {name = "Innkeeper Janene", ID = 6272, friendlyAlliance = true, friendlyHorde = false, location = 1445},
    {name = "Innkeeper Shay", ID = 2388, friendlyAlliance = false, friendlyHorde = true, location = 1445},
    -- Swamp of Sorrows (1435)
    {name = "Thultash", ID = 982, friendlyAlliance = true, friendlyHorde = false, location = 1435},
    -- Felwood (1448)
    {name = "Innkeeper Shyria", ID = 11116, friendlyAlliance = true, friendlyHorde = false, location = 1448},
    -- Winterspring (1452)
    {name = "Himmik", ID = 11187, friendlyAlliance = true, friendlyHorde = true, location = 1452},
    -- Duskwood (1431)
    {name = "Innkeeper Trelayne", ID = 6791, friendlyAlliance = true, friendlyHorde = false, location = 1431},
    -- Thousand Needles (1441)
    {name = "Laer Stepperunner", ID = 3689, friendlyAlliance = false, friendlyHorde = true, location = 1441},
    -- Eastern Plaguelands (1423)
    {name = "Innkeeper Bates", ID = 16256, friendlyAlliance = true, friendlyHorde = false, location = 1423},
    -- Arathi Highlands (1417)
    {name = "Innkeeper Kimlya", ID = 9501, friendlyAlliance = true, friendlyHorde = false, location = 1417},
    -- Wetlands (1437)
    {name = "Innkeeper Helbrek", ID = 14624, friendlyAlliance = true, friendlyHorde = false, location = 1437},
    -- Western Plaguelands (1422)
    {name = "Innkeeper Lyshaerya", ID = 12959, friendlyAlliance = true, friendlyHorde = false, location = 1422},
    -- Un'Goro Crater (1449)
    {name = "Innkeeper Karakul", ID = 11118, friendlyAlliance = true, friendlyHorde = true, location = 1449},
    -- Stonetalon Mountains (1442)
    {name = "Innkeeper Jayka", ID = 7731, friendlyAlliance = false, friendlyHorde = true, location = 1442},
    -- Searing Gorge (1427)
    {name = "Innkeeper Grilka", ID = 12944, friendlyAlliance = false, friendlyHorde = true, location = 1427},
    -- Tanaris (1446)
    {name = "Innkeeper Fizzgrimble", ID = 7733, friendlyAlliance = true, friendlyHorde = false, location = 1446},
    {name = "Innkeeper Shul'kar", ID = 9356, friendlyAlliance = false, friendlyHorde = true, location = 1446},
    -- Blasted Lands (1419)
    {name = "Bernie Heisten", ID = 3546, friendlyAlliance = true, friendlyHorde = true, location = 1419},
    -- Burning Steppes (1428)
    {name = "Gabrielle Chase", ID = 3298, friendlyAlliance = true, friendlyHorde = false, location = 1428},
    -- Silverpine Forest (1421)
    {name = "Innkeeper Bates", ID = 16256, friendlyAlliance = false, friendlyHorde = true, location = 1421},
    -- Westfall (1436)
    {name = "Innkeeper Heather", ID = 8931, friendlyAlliance = true, friendlyHorde = false, location = 1436},
    -- Moonglade (1450)
    {name = "Dargon", ID = 12019, friendlyAlliance = true, friendlyHorde = true, location = 1450},
    {name = "My'lanna", ID = 12026, friendlyAlliance = true, friendlyHorde = true, location = 1450},
    -- Redridge Mountains (1433)
    {name = "Bartender Wental", ID = 5620, friendlyAlliance = false, friendlyHorde = true, location = 1433},
    -- Darkshore (1439)
    {name = "Tiyani", ID = 4195, friendlyAlliance = true, friendlyHorde = false, location = 1439},
    -- Loch Modan (1432)
    {name = "Innkeeper Hearthstove", ID = 6734, friendlyAlliance = true, friendlyHorde = false, location = 1432},
    -- Elwynn Forest (1429)
    {name = "Innkeeper Farley", ID = 295, friendlyAlliance = true, friendlyHorde = false, location = 1429},
    -- Tirisfal Glades (1420)
    {name = "Innkeeper Renee", ID = 5688, friendlyAlliance = false, friendlyHorde = true, location = 1420},
    -- Dun Morogh (1426)
    {name = "Kazan Mogosh", ID = 1237, friendlyAlliance = true, friendlyHorde = false, location = 1426},
    -- Mulgore (1412)
    {name = "Innkeeper Kauth", ID = 6746, friendlyAlliance = false, friendlyHorde = true, location = 1412},
    -- Teldrassil (1438)
    {name = "Dellylah", ID = 6091, friendlyAlliance = true, friendlyHorde = false, location = 1438},
    -- Durotar (1411)
    {name = "Innkeeper Grosk", ID = 6928, friendlyAlliance = false, friendlyHorde = true, location = 1411},
}
function SetVendor()
    local zone = GetZoneID()
    Log(zone)
    Log(Player:IsAlliance())
    local faction -- Declare once here
    if Player:IsAlliance() == true then
        faction = "Alliance"
        Log("For the Alliance!")
    else
        faction = "Horde"
        Log("For the Horde!")
    end
    Log("Faction:" .. faction)
    local playerPos = UnitPosToFloatArray(GetPlayer())
    local bestVendor = nil

    -- Try to find a vendor in the same zone and for the player's faction
    for _, vendor in ipairs(Vendors) do
        if vendor.location == zone then
            if (faction == "Alliance" and vendor.friendlyAlliance) or (faction == "Horde" and vendor.friendlyHorde) then
                Vendor = vendor
                print("Selected Vendor: " .. Vendor.name)
                return
            end
        end
    end

    -- If not found, find the closest vendor for the player's faction
    local minDist = math.huge
    for _, vendor in ipairs(Vendors) do
        if (faction == "Alliance" and vendor.friendlyAlliance) or (faction == "Horde" and vendor.friendlyHorde) then
            local vendorPos = GetNPCPostionFromDB(vendor.ID)
            if vendorPos and playerPos then
                local dist = DistanceBetweenPoints(playerPos, vendorPos)
                if dist < minDist then
                    minDist = dist
                    bestVendor = vendor
                end
            end
        end
    end

    if bestVendor then
        Vendor = bestVendor
        print("Selected closest Vendor: " .. Vendor.name)
    else
        print("No suitable vendor found for your faction.")
        Vendor = nil
    end
    Log("This isn't working!")
end
function SetFoodAndDrink()
    if Player.Class == "Warrior" or Player.Class == "Rogue" then
        Drink = nil
    else
        local bestDrink = Drink[1]
        for i = 1, #Drink do
            if Drink[i].level <= Player.Level and Drink[i].level > bestDrink.level then
                bestDrink = Drink[i]
            end
        end
        SelectedDrink = bestDrink
    end
    for i = 1, #Food do
        if Food[i].level <= Player.Level then
            SelectedFood = Food[i]
        end
    end
    if Drink == nil then
        print("No suitable drink found for your class.")
    else
        print("Selected Drink: " .. SelectedDrink.name)
        SetDrink(SelectedDrink.name, 40)
    end
    if SelectedFood then
        print("Selected Food: " .. SelectedFood.name)
        SetFood(SelectedFood.name, 40)
    else
        print("No suitable food found for your level.")
    end
end
function Override()
    if Drink ~= nil and SelectedDrink ~= nil then
        if ItemCount(SelectedDrink.name) < 5 then
            return false
        end
    end
    if SelectedFood ~= nil then
        if ItemCount(SelectedFood.name) < 5 then
            return false
        end
    end
    return true
end
function SellAtVendor()
    if not Vendor then
        print("Error: No vendor selected.")
        return
    end
    local pos = GetNPCPostionFromDB(Vendor.ID)
    if pos then
        QuestGoToPoint(pos[0], pos[1], pos[2], false, true)
        local unit = FindUnitByName(Vendor.name)
        if unit then
            FindMeshPathToUnit(unit)
            InteractWithUnit(unit)
            SleepPlugin(3000)
        else
            print("Error: Vendor " .. Vendor.name .. " not found.")
        end
    else
        print("Error: Could not get position for vendor " .. Vendor.name)
    end
end

SetFoodAndDrink()
--Grind and Gather goes here--
SetVendor()
SellAtVendor()

local Waypoints = {
    {3581.20337,-4603.72656,103.50853},
    {3614.72656,-4644.39,114.010559},
    {3650.38916,-4685.472,117.788185},
    {3682.04468,-4730.784,120.962753},
    {3722.18555,-4769.5625,132.748276},
    {3732.55762,-4821.278,132.184479},
    {3726.97168,-4876.96436,125.394623},
    {3724.37134,-4931.782,131.716141},
    {3772.65283,-4949.38672,142.238831},
    {3819.05371,-4959.964,143.304077},
    {3824.35742,-5014.07373,136.008942},
    {3875.92456,-5032.94531,132.509689},
    {3922.211,-5063.023,128.17276},
    {3964.62622,-5098.378,117.719841},
    {3993.685,-5146.238,110.212379},
    {4023.27881,-5193.52832,113.333992},
    {4051.0835,-5242.122,105.3959},
    {4088.01514,-5283.85742,104.9083},
    {4127.941,-5323.138,109.894157},
    {4177.569,-5347.151,113.435257},
    {4226.861,-5372.78857,116.850037},
    {4279.896,-5380.232,116.742142},
    {4334.345,-5393.429,117.122017},
    {4387.04443,-5410.99561,113.897163},
    {4437.60742,-5434.87256,108.924858},
    {4464.78955,-5482.915,108.931755},
    {4514.435,-5508.291,111.474083},
    {4549.62549,-5548.532,103.67411},
    {4561.25928,-5603.022,102.450394},
    {4586.626,-5651.742,104.547867},
    {4555.58252,-5697.981,98.66095},
    {4522.299,-5743.003,102.498756},
    {4481.66748,-5779.23047,103.596184},
    {4426.667,-5789.295,106.412422},
    {4377.368,-5814.4707,100.877365},
    {4329.95557,-5844.27051,97.93976},
    {4287.85547,-5876.864,96.4243546},
    {4293.53662,-5931.678,96.621376},
    {4304.28,-5986.6333,97.44401},
    {4345.013,-6021.59131,99.29324},
    {4400.82764,-6022.214,96.32212},
    {4438.118,-6057.84326,96.34812},
    {4469.954,-6102.6167,94.64873},
    {4479.929,-6157.42529,95.31495},
    {4497.41943,-6210.622,98.77438},
    {4520.645,-6261.29443,104.271904},
    {4541.74658,-6313.03857,115.600494},
    {4557.2373,-6366.64648,126.251961},
    {4553.37744,-6422.369,116.674934},
    {4547.64551,-6478.075,105.3964},
    {4541.819,-6533.78467,92.67391},
    {4515.48633,-6581.86963,96.40646},
    {4480.3916,-6625.02344,96.1151},
    {4454.63135,-6674.64648,97.9270859},
    {4431.765,-6725.765,93.07761},
    {4433.371,-6780.127,96.46832},
    {4384.65137,-6806.08838,96.2180939},
    {4341.348,-6840.17139,93.72223},
    {4302.677,-6880.67432,94.36595},
    {4273.398,-6927.8623,97.91392},
    {4240.354,-6973.087,94.9592056},
    {4207.241,-7018.248,95.1033554},
    {4189.53125,-7062.421,102.363182},
    {4225.42139,-7037.45264,99.17063},
    {4251.238,-6989.099,100.164368},
    {4285.406,-6944.731,102.610695},
    {4319.379,-6900.224,97.91017},
    {4349.771,-6853.2,94.7654343},
    {4380.168,-6806.168,95.60392},
    {4383.19141,-6775.83643,99.6288147},
    {4408.702,-6772.37939,100.010231},
    {4430.3833,-6729.212,93.4255753},
    {4416.345,-6675.90039,99.54503},
    {4424.04248,-6620.43164,102.082962},
    {4431.741,-6564.951,101.757568},
    {4453.20752,-6514.924,110.343987},
    {4487.7207,-6470.828,123.476418},
    {4523.42236,-6428.446,116.076363},
    {4546.308,-6377.379,125.393036},
    {4511.096,-6334.893,121.005257},
    {4495.89746,-6283.461,112.455444},
    {4520.723,-6235.0,100.955826},
    {4505.15,-6183.267,93.7449646},
    {4451.809,-6199.72,95.94032},
    {4398.05,-6215.261,95.76251},
    {4344.14355,-6214.23975,95.3417},
    {4297.692,-6232.467,108.302071},
    {4300.724,-6219.475,109.953568},
    {4352.828,-6211.953,94.67382},
    {4403.577,-6206.175,94.64802},
    {4453.105,-6180.57471,93.79124},
    {4497.42041,-6147.21338,95.81563},
    {4523.193,-6102.307,99.46269},
    {4475.24951,-6073.863,95.38077},
    {4426.689,-6045.52539,93.03688},
    {4378.51563,-6017.41357,97.3607559},
    {4330.154,-5989.192,98.45366},
    {4281.78662,-5960.96729,96.52609},
    {4242.142,-5922.2207,96.55467},
    {4187.65674,-5920.492,97.21156},
    {4166.915,-5900.97656,100.052666},
    {4212.64941,-5905.257,101.749519},
    {4264.71729,-5885.254,95.68039},
    {4293.03369,-5843.197,96.6904},
    {4272.606,-5793.38965,102.939224},
    {4233.21729,-5759.511,108.126373},
    {4186.472,-5730.279,118.425186},
    {4155.708,-5688.8335,123.2554},
    {4169.94043,-5636.52539,114.375191},
    {4192.24756,-5588.37,113.222328},
    {4157.72559,-5548.13037,105.817734},
    {4112.6333,-5515.401,103.444183},
    {4088.36548,-5465.49,108.489265},
    {4049.14282,-5425.85938,113.140244},
    {4015.30859,-5381.257,116.948845},
    {3980.63867,-5337.39844,125.273994},
    {3937.14038,-5302.123,127.266319},
    {3911.49731,-5262.91553,130.546936},
    {3951.376,-5244.4165,118.164055},
    {3927.08081,-5196.132,121.542549},
    {3901.79053,-5193.15332,126.339615},
    {3884.97827,-5141.653,129.03389},
    {3846.06445,-5103.43,134.963455},
    {3816.80469,-5136.075,136.763245},
    {3797.45728,-5178.904,141.468353},
    {3793.36377,-5189.904,137.660248},
    {3812.89282,-5107.864,133.663071},
    {3818.826,-5053.362,133.679565},
    {3802.66333,-5000.395,139.70256},
    {3773.1438,-4959.79639,142.508072},
    {3721.12183,-4939.338,132.211838},
    {3669.78,-4916.997,127.535805},
    {3620.35718,-4890.869,126.572548},
    {3601.71118,-4841.353,121.834709},
    {3588.16675,-4790.92334,118.9626},
    {3533.68823,-4785.205,112.840057},
    {3481.01733,-4770.49365,112.727921},
    {3430.7478,-4780.004,108.149078},
    {3402.448,-4828.01953,113.587509},
    {3388.96948,-4870.352,118.361115},
    {3420.1748,-4911.191,119.652077},
    {3467.2334,-4936.51172,105.993675},
    {3494.9043,-4982.947,91.62943},
    {3501.517,-5036.878,86.18649},
    {3511.82715,-5090.89355,81.88542},
    {3553.35474,-5127.69727,82.52636},
    {3603.143,-5153.07227,80.50068},
    {3656.36719,-5170.485,79.78021},
    {3692.66846,-5206.1875,81.19616},
    {3719.92676,-5254.84375,85.1515961},
    {3740.30615,-5298.30127,85.583374},
    {3721.92676,-5349.057,72.07511},
    {3709.131,-5403.4624,56.8340454},
    {3683.51123,-5445.54248,41.4436531},
    {3660.44385,-5494.04,31.3234787},
    {3636.49951,-5535.949,22.22375},
    {3584.472,-5556.51953,18.2252235},
    {3543.63574,-5589.821,12.70888},
    {3487.707,-5592.302,10.0370827},
    {3431.83032,-5595.978,11.5759735},
    {3377.67334,-5609.559,7.38438845},
    {3324.2168,-5626.173,10.389492},
    {3275.62451,-5653.15039,11.7386923},
    {3235.82983,-5692.551,10.2326221},
    {3202.36768,-5736.28027,11.27141},
    {3153.73218,-5761.53955,13.8464432},
    {3132.32983,-5723.889,23.1614323},
    {3174.58276,-5688.278,24.0477123},
    {3222.949,-5661.009,17.33692},
    {3272.751,-5635.46729,13.6417217},
    {3327.11328,-5622.927,10.6420374},
    {3381.68018,-5610.33936,7.03615952},
    {3487.519,-5585.68457,11.3091049},
    {3543.45947,-5591.22168,12.6459379},
    {3595.81982,-5610.343,11.0167322},
    {3647.52856,-5631.489,7.587554},
    {3665.25146,-5614.269,7.9430666},
    {3633.54,-5570.329,17.8692169},
    {3595.20361,-5540.76855,20.3706074},
    {3627.862,-5532.822,21.940834},
    {3655.10645,-5489.53955,33.0127029},
    {3683.58521,-5442.251,42.31801},
    {3708.9353,-5394.76855,59.087616},
    {3722.62231,-5340.73438,75.3803253},
    {3706.44067,-5289.9917,88.50611},
    {3700.71924,-5234.456,85.64813},
    {3672.84424,-5187.22168,81.09869},
    {3627.55835,-5155.65527,80.13092},
    {3575.144,-5139.82861,81.51515},
    {3528.054,-5109.594,82.377655},
    {3490.79761,-5073.166,85.30841},
    {3435.28516,-5076.866,82.79946},
    {3380.09253,-5084.111,87.1524048},
    {3330.50342,-5106.276,88.4732056},
    {3299.86353,-5145.422,88.1605759},
    {3268.98047,-5180.6,88.5496445},
    {3262.52881,-5233.459,85.99442},
    {3223.18164,-5268.219,85.90131},
    {3197.09717,-5316.174,85.1179047},
    {3186.05884,-5365.24658,84.81178},
    {3173.23853,-5395.548,88.52976},
    {3135.17969,-5371.723,88.44768},
    {3083.19922,-5357.286,98.2133255},
    {3186.71582,-5362.571,84.65359},
    {3182.83423,-5311.798,86.8111649},
    {3156.77979,-5265.163,91.19585},
    {3101.11938,-5262.36768,91.8862839},
    {3051.87964,-5286.01025,93.1752243},
    {3144.871,-5265.223,91.54102},
    {3200.293,-5269.65527,88.32291},
    {3241.41,-5235.20654,85.68791},
    {3260.77271,-5183.85059,87.47683},
    {3306.29639,-5156.77246,86.82616},
    {3343.92236,-5124.64844,87.2735062},
    {3376.81348,-5080.118,89.67337},
    {3413.4873,-5051.698,86.8946},
    {3397.62427,-5027.32666,87.60153},
    {3352.39722,-4994.52246,89.20128},
    {3349.00732,-4939.11475,92.01163},
    {3325.90625,-4901.61133,108.204437},
    {3282.83325,-4910.866,118.402695},
    {3267.96729,-4964.598,124.700218},
    {3227.24268,-5000.724,130.635223},
    {3174.603,-5015.65,142.155212},
    {3133.35278,-5050.71338,139.634338},
    {3114.53882,-5103.247,133.472717},
    {3102.99438,-5158.025,134.968124},
    {3048.9624,-5163.14063,132.1079},
    {3017.05347,-5203.793,133.339676},
    {2962.94214,-5211.855,131.156525},
    {2913.5564,-5237.01855,127.749557},
    {2921.94849,-5282.18,131.821335},
    {2958.78418,-5323.79834,129.637329},
    {2961.40063,-5366.542,132.765366},
    {2916.67358,-5399.29834,116.361458},
    {2872.4624,-5433.379,108.194153},
    {2828.618,-5467.82764,102.239685},
    {2781.947,-5499.15967,100.95916},
    {2731.39624,-5516.961,103.573318},
    {2676.68213,-5527.961,99.4402161},
    {2623.654,-5545.921,105.286606},
    {2574.82544,-5572.739,109.307838},
    {2552.1106,-5621.86865,110.990059},
    {2555.92944,-5677.59375,106.509666},
    {2562.0376,-5733.30469,101.074005},
    {2566.22852,-5788.90869,101.0214},
    {2570.06226,-5844.9834,96.99381},
    {2572.50513,-5900.69873,93.85885},
    {2570.34985,-5956.233,96.17291},
    {2545.307,-6006.05859,97.34988},
    {2521.10449,-6056.62256,98.5946045},
    {2496.26221,-6106.36,100.2642},
    {2487.416,-6160.758,105.578545},
    {2492.356,-6214.93652,103.867874},
    {2522.91675,-6259.933,102.660553},
    {2575.95386,-6277.01367,99.8543},
    {2622.57544,-6252.747,91.59238},
    {2660.14258,-6211.24561,89.49386},
    {2649.16187,-6158.435,99.31195},
    {2647.238,-6103.013,99.00296},
    {2637.80225,-6047.82666,100.734207},
    {2647.44287,-5993.70654,99.43253},
    {2671.13159,-5944.694,94.84587},
    {2708.4668,-5903.117,97.3725739},
    {2743.051,-5860.20166,95.65863},
    {2781.63354,-5826.06934,93.41761},
    {2779.28125,-5770.73975,108.25798},
    {2808.85718,-5723.373,123.687965},
    {2831.42017,-5673.10645,127.211678},
    {2844.88721,-5618.74951,125.190987},
    {2860.096,-5564.993,131.148544},
    {2895.45972,-5527.8877,143.584839},
    {2930.98169,-5557.6626,144.7017},
    {2901.10376,-5561.97852,141.57457},
    {2849.2605,-5561.089,130.453049},
    {2806.26123,-5585.13428,128.054962},
    {2753.46265,-5574.234,124.469376},
    {2699.916,-5587.025,118.854492},
    {2659.95044,-5555.585,103.135933},
    {2692.74756,-5513.557,101.147476},
    {2747.96655,-5504.652,102.487556},
    {2802.341,-5492.00635,99.8391},
    {2851.137,-5464.53467,108.988243},
    {2891.29443,-5427.43457,115.9594},
    {2926.62,-5390.088,122.161774},
    {2921.21777,-5335.037,121.819191},
    {2918.3396,-5279.625,132.097122},
    {2919.28687,-5226.25928,126.929062},
    {2960.74878,-5195.113,127.611038},
    {3009.43213,-5167.69727,129.845337},
    {3044.216,-5125.79639,129.725769},
    {3082.148,-5090.56,136.334976},
    {3120.51978,-5053.269,141.16188},
    {3165.13428,-5020.30273,143.410065},
    {3218.62378,-5005.44336,130.778748},
    {3257.65,-4970.28564,126.719246},
    {3274.92236,-4917.01563,117.544708},
    {3292.19482,-4863.746,113.121422},
    {3302.95776,-4808.916,108.435852},
    {3311.90137,-4753.635,100.8263},
    {3336.82422,-4705.73535,98.39733},
    {3378.36841,-4668.184,95.74067},
    {3411.953,-4664.83057,101.433968}
}

local TargetNames = {
    "Golden Sansam", "Purple Lotus", "Goldthorn", "Sungrass", "Mountain Silversage", "Dreamfoil", "Mithril Deposit", "Truesilver Deposit", "Rich Thorium Vein"
}

SetFoodAndDrink()
GrindAndGatherPath(TableToStringList(TargetNames), TableToVecList(Waypoints), 40, false, "Override")
SetVendor()
SellAtVendor()
