---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Plainstrider")
StartMobAvoidance()

--- Setting Waypoints ---
local Waypoints = {}
Waypoints[1] = {-3135.068,-297.9706,39.13219}
Waypoints[2] = {-3097.992,-427.3322,33.49492}
Waypoints[3] = {-2938.277,-454.5663,50.89686}

--- Setting Vendor ---
UseDBToRepair(false)
UseDBToSell(true)
local VendorIDs = {}
VendorIDs[1] = 3075

SetQuestRepairVendors(TableToList(VendorIDs))

local TargetNames = {}
TargetNames[1] = "Plainstrider" 

GrindAndGatherPath(TableToStringList(TargetNames),TableToVecList(Waypoints),80)

ZoneProfiles["Mulgore1-3"] = {
    Waypoints = {
        {-3135.068,-297.9706,39.13219},
        {-3097.992,-427.3322,33.49492},
        {-2938.277,-454.5663,50.89686}
    },
    VendorIDs = {3075},
    TargetNames = {"Plainstrider"},
    MinLevel = 1,
    MaxLevel = 3,
    Range = 80
}