---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Mottled Boar")
StartMobAvoidance()

--- Setting Waypoints ---
local Waypoints = {}
Waypoints[1] = {-422.769,-4296.835,44.44546}
Waypoints[2] = {-405.6567,-4212.864,54.68137}
Waypoints[3] = {-596.7441,-4364.921,41.20194}

--- Setting Vendor ---
UseDBToRepair(false)
UseDBToSell(true)
local VendorIDs = {}
VendorIDs[1] = 3160

SetQuestRepairVendors(TableToList(VendorIDs))

local TargetNames = {}
TargetNames[1] = "Mottled Boar" 

GrindAndGatherPath(TableToStringList(TargetNames),TableToVecList(Waypoints),80)

ZoneProfiles["Durotar1-3"] = {
    Waypoints = {
        {-422.769,-4296.835,44.44546},
        {-405.6567,-4212.864,54.68137},
        {-596.7441,-4364.921,41.20194}
    },
    VendorIDs = {3160},
    TargetNames = {"Mottled Boar"},
    MinLevel = 1,
    MaxLevel = 3,
    Range = 80
}