---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Mindless Zombie")
AddNameToAvoidWhiteList("Wretched Zombie")

StartMobAvoidance()

--- Setting Waypoints ---
local Waypoints = {}
Waypoints[1] = {1938.728,1656.072,269.0298}
Waypoints[2] = {1878.835,1646.994,173.1242}

--- Setting Vendor ---
UseDBToRepair(false)
UseDBToSell(true)
local VendorIDs = {}
VendorIDs[1] = 2117

SetQuestRepairVendors(TableToList(VendorIDs))

local TargetNames = {}
TargetNames[1] = "Mindless Zombie"
TargetNames[2] = "Wretched Zombie" 

GrindAndGatherPath(TableToStringList(TargetNames),TableToVecList(Waypoints),80)

ZoneProfiles["Tirisfal1-3"] = {
    Waypoints = {
        {1938.728,1656.072,269.0298},
        {1878.835,1646.994,173.1242}
    },
    VendorIDs = {2117},
    TargetNames = {"Mindless Zombie", "Wretched Zombie"},
    MinLevel = 1,
    MaxLevel = 3,
    Range = 80
}