---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Wandering Spirit")
AddNameToAvoidWhiteList("Bleeding Horror")
AddNameToAvoidWhiteList("Vampiric Duskbat")
StartMobAvoidance()

--- Setting Waypoints ---
local Waypoints = {}
Waypoints[1] = {1990.243,-247.3323,35.02586}
Waypoints[2] = {2020.546,-333.9989,36.20387}

--- Setting Vendor ---
UseDBToRepair(false)
UseDBToSell(true)
local VendorIDs = {}
VendorIDs[1] = 2137

SetQuestRepairVendors(TableToList(VendorIDs))

local TargetNames = {}
TargetNames[1] = "Wandering Spirit" 
TargetNames[2] = "Bleeding Horror" 
TargetNames[3] = "Vampiric Duskbat" 

GrindAndGatherPath(TableToStringList(TargetNames),TableToVecList(Waypoints),80)

ZoneProfiles["Tirisfal10-13"] = {
    Waypoints = {
        {1990.243,-247.3323,35.02586},
        {2020.546,-333.9989,36.20387}
    },
    VendorIDs = {2137},
    TargetNames = {"Wandering Spirit", "Bleeding Horror", "Vampiric Duskbat"},
    MinLevel = 10,
    MaxLevel = 13,
    Range = 80
}

