---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Zhevra Runner")
AddNameToAvoidWhiteList("Sunscale Screecher")
AddNameToAvoidWhiteList("Fleeting Plainstrider")
AddNameToAvoidWhiteList("Sunscale Lashtail")
AddNameToAvoidWhiteList("Greater Plainstrider")
AddNameToAvoidWhiteList("Savannah Huntress")
StartMobAvoidance()

--- Setting Waypoints ---
local Waypoints = {}
Waypoints[1] = {-409.7565,-2840.666,94.25677}
Waypoints[2] = {-694.605,-2809.554,95.65337}

--- Setting Vendor ---
UseDBToRepair(false)
UseDBToSell(true)
local VendorIDs = {}
VendorIDs[1] = 3486

SetQuestRepairVendors(TableToList(VendorIDs))

local TargetNames = {}
TargetNames[1] = "Zhevra Runner" 
TargetNames[2] = "Sunscale Screecher" 
TargetNames[3] = "Fleeting Plainstrider" 
TargetNames[4] = "Sunscale Lashtail" 
TargetNames[5] = "Greater Plainstrider" 
TargetNames[6] = "Savannah Huntress" 

GrindAndGatherPath(TableToStringList(TargetNames),TableToVecList(Waypoints),80)

ZoneProfiles["Barrens13-16"] = {
    Waypoints = {
        {-409.7565,-2840.666,94.25677},
        {-694.605,-2809.554,95.65337}
    },
    VendorIDs = {3486},
    TargetNames = {"Zhevra Runner", "Sunscale Screecher", "Fleeting Plainstrider", "Sunscale Lashtail", "Greater Plainstrider", "Savannah Huntress"},
    MinLevel = 13,
    MaxLevel = 16,
    Range = 80
}