---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Zhevra Charger")
AddNameToAvoidWhiteList("Ornery Plainstrider")
AddNameToAvoidWhiteList("Savannah Patriarch")
AddNameToAvoidWhiteList("Sunscale Scytheclaw")
StartMobAvoidance()

--- Setting Waypoints ---
local Waypoints = {}
Waypoints[1] = {569.0314,-1818.443,92.62054}
Waypoints[2] = {647.8192,-1951.777,93.26044}

--- Setting Vendor ---
UseDBToRepair(false)
UseDBToSell(true)
local VendorIDs = {}
VendorIDs[1] = 3682

SetQuestRepairVendors(TableToList(VendorIDs))

local TargetNames = {}
TargetNames[1] = "Zhevra Charger" 
TargetNames[2] = "Ornery Plainstrider" 
TargetNames[3] = "Savannah Patriarch" 
TargetNames[4] = "Sunscale Scytheclaw" 

GrindAndGatherPath(TableToStringList(TargetNames),TableToVecList(Waypoints),80)

ZoneProfiles["Barrens16-21"] = {
    Waypoints = {
        {569.0314,-1818.443,92.62054},
        {647.8192,-1951.777,93.26044}
    },
    VendorIDs = {3682},
    TargetNames = {"Zhevra Charger", "Ornery Plainstrider", "Savannah Patriarch", "Sunscale Scytheclaw"},
    MinLevel = 16,
    MaxLevel = 21,
    Range = 80
}