---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Zhevra Courser")
AddNameToAvoidWhiteList("Thunderhead")
AddNameToAvoidWhiteList("Thunderhawk Cloudscraper")
StartMobAvoidance()

--- Setting Waypoints ---
local Waypoints = {}
Waypoints[1] = {-2479.396,-2282.147,93.53313}
Waypoints[2] = {-2616.538,-2004.369,93.41865}
Waypoints[3] = {-2535.269,-1819.184,92.89848}

--- Setting Vendor ---
UseDBToRepair(false)
UseDBToSell(true)
local VendorIDs = {}
VendorIDs[1] = 10380

SetQuestRepairVendors(TableToList(VendorIDs))

local TargetNames = {}
TargetNames[1] = "Zhevra Courser" 
TargetNames[2] = "Thunderhead" 
TargetNames[3] = "Thunderhawk Cloudscraper" 

GrindAndGatherPath(TableToStringList(TargetNames),TableToVecList(Waypoints),80)

ZoneProfiles["Barrens21-25"] = {
    Waypoints = {
        {-2479.396,-2282.147,93.53313},
        {-2616.538,-2004.369,93.41865},
        {-2535.269,-1819.184,92.89848}
    },
    VendorIDs = {10380},
    TargetNames = {"Zhevra Courser", "Thunderhead", "Thunderhawk Cloudscraper"},
    MinLevel = 21,
    MaxLevel = 25,
    Range = 80
}