---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Laughing Sister")
StartMobAvoidance()

--- Setting Waypoints ---
local Waypoints = {}
Waypoints[1] = {2553.88,-1705.11,152.5567}
Waypoints[2] = {2653.88,-1820.666,191.213}

--- Setting Vendor ---
UseDBToRepair(false)
UseDBToSell(true)
local VendorIDs = {}
VendorIDs[1] = 6028

SetQuestRepairVendors(TableToList(VendorIDs))

local TargetNames = {}
TargetNames[1] = "Laughing Sister" 

GrindAndGatherPath(TableToStringList(TargetNames),TableToVecList(Waypoints),80)

ZoneProfiles["Ashenvale25-29"] = {
    Waypoints = {
        {2553.88,-1705.11,152.5567},
        {2653.88,-1820.666,191.213}
    },
    VendorIDs = {6028},
    TargetNames = {"Laughing Sister"},
    MinLevel = 25,
    MaxLevel = 29,
    Range = 80
}