---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Elder Shadowhorn Stag")
AddNameToAvoidWhiteList("Ghostpaw Alpha")
StartMobAvoidance()

--- Setting Waypoints ---
local Waypoints = {}
Waypoints[1] = {2056.477,-2222.888,134.3038}
Waypoints[2] = {2518.699,-2482.147,168.5119}
Waypoints[3] = {2610.128,-2722.888,149.1172}
Waypoints[4] = {2188.541,-2308.073,102.6115}

--- Setting Vendor ---
UseDBToRepair(false)
UseDBToSell(true)
local VendorIDs = {}
VendorIDs[1] = 6028

SetQuestRepairVendors(TableToList(VendorIDs))

local TargetNames = {}
TargetNames[1] = "Elder Shadowhorn Stag" 
TargetNames[2] = "Ghostpaw Alpha" 

GrindAndGatherPath(TableToStringList(TargetNames),TableToVecList(Waypoints),80)

ZoneProfiles["Ashenvale27-32"] = {
    Waypoints = {
        {2056.477,-2222.888,134.3038},
        {2518.699,-2482.147,168.5119},
        {2610.128,-2722.888,149.1172},
        {2188.541,-2308.073,102.6115}
    },
    VendorIDs = {6028},
    TargetNames = {"Elder Shadowhorn Stag", "Ghostpaw Alpha"},
    MinLevel = 27,
    MaxLevel = 32,
    Range = 80
}