---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Bleakheart Trickster")
AddNameToAvoidWhiteList("Bleakheart Satyr")
AddNameToAvoidWhiteList("Bleakheart Hellcaller")

StartMobAvoidance()

--- Setting Waypoints ---
local Waypoints = {}
Waypoints[1] = {2778.122,-2920.314,148.1487}
Waypoints[2] = {2762.971,-3009.08,150.9476}
Waypoints[3] = {2708.425,-2980.231,141.0394}

--- Setting Vendor ---
UseDBToRepair(false)
UseDBToSell(true)
local VendorIDs = {}
VendorIDs[1] = 6028

SetQuestRepairVendors(TableToList(VendorIDs))

local TargetNames = {}
TargetNames[1] = "Bleakheart Trickster" 
TargetNames[2] = "Bleakheart Satyr"
TargetNames[3] = "Bleakheart Hellcaller"


GrindAndGatherPath(TableToStringList(TargetNames),TableToVecList(Waypoints),80)

ZoneProfiles["Ashenvale28-35"] = {
    Waypoints = {
        {2778.122,-2920.314,148.1487},
        {2762.971,-3009.08,150.9476},
        {2708.425,-2980.231,141.0394}
    },
    VendorIDs = {6028},
    TargetNames = {"Bleakheart Trickster", "Bleakheart Satyr", "Bleakheart Hellcaller"},
    MinLevel = 28,
    MaxLevel = 35,
    Range = 80
}