---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Felguard")
AddNameToAvoidWhiteList("Searing Infernal")
AddNameToAvoidWhiteList("Mannoroc Lasher")
StartMobAvoidance()

--- Setting Waypoints ---
local Waypoints = {}
Waypoints[1] = {1999.334,-2973.999,108.8258}
Waypoints[2] = {2014.486,-3087.332,105.4874}
Waypoints[3] = {2111.456,-3082.888,109.7428}
Waypoints[4] = {2081.153,-2996.221,112.1678}

--- Setting Vendor ---
UseDBToRepair(false)
UseDBToSell(true)
local VendorIDs = {}
VendorIDs[1] = 6028

SetQuestRepairVendors(TableToList(VendorIDs))

local TargetNames = {}
TargetNames[1] = "Felguard" 
TargetNames[2] = "Searing Infernal" 
TargetNames[3] = "Mannoroc Lasher" 

GrindAndGatherPath(TableToStringList(TargetNames),TableToVecList(Waypoints),80)

ZoneProfiles["Ashenvale29-35"] = {
    Waypoints = {
        {1999.334,-2973.999,108.8258},
        {2014.486,-3087.332,105.4874},
        {2111.456,-3082.888,109.7428},
        {2081.153,-2996.221,112.1678}
    },
    VendorIDs = {6028},
    TargetNames = {"Felguard", "Searing Infernal", "Mannoroc Lasher"},
    MinLevel = 29,
    MaxLevel = 35,
    Range = 80
}