---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Scorpid Worker")
StartMobAvoidance()

--- Setting Waypoints ---
local Waypoints = {}
Waypoints[1] = {-411.3607,-4097.119,50.73689}
Waypoints[2] = {-220.2734,-4217.403,60.44237}
Waypoints[3] = {-334.3555,-4433.006,55.1583}

--- Setting Vendor ---
UseDBToRepair(false)
UseDBToSell(true)
local VendorIDs = {}
VendorIDs[1] = 3160

SetQuestRepairVendors(TableToList(VendorIDs))

local TargetNames = {}
TargetNames[1] = "Scorpid Worker" 

GrindAndGatherPath(TableToStringList(TargetNames),TableToVecList(Waypoints),80)

ZoneProfiles["Durotar3-5"] = {
    Waypoints = {
        {-411.3607,-4097.119,50.73689},
        {-220.2734,-4217.403,60.44237},
        {-334.3555,-4433.006,55.1583}
    },
    VendorIDs = {3160},
    TargetNames = {"Scorpid Worker"},
    MinLevel = 3,
    MaxLevel = 5,
    Range = 80
}