---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Rattlecage Skeleton")
AddNameToAvoidWhiteList("Ragged Scavenger")
AddNameToAvoidWhiteList("Mangy Duskbat")
StartMobAvoidance()

--- Setting Waypoints ---
local Waypoints = {}
Waypoints[1] = {2095.591,1510.824,70.05881}
Waypoints[2] = {2032.846,1440.469,64.66148}
Waypoints[3] = {1955.84,1374.653,67.30131}

--- Setting Vendor ---
UseDBToRepair(false)
UseDBToSell(true)
local VendorIDs = {}
VendorIDs[1] = 2113

SetQuestRepairVendors(TableToList(VendorIDs))

local TargetNames = {}
TargetNames[1] = "Rattlecage Skeleton" 
TargetNames[2] = "Ragged Scavenger" 
TargetNames[3] = "Mangy Duskbat" 

GrindAndGatherPath(TableToStringList(TargetNames),TableToVecList(Waypoints),80)

ZoneProfiles["Tirisfal3-5"] = {
    Waypoints = {
        {2095.591,1510.824,70.05881},
        {2032.846,1440.469,64.66148},
        {1955.84,1374.653,67.30131}
    },
    VendorIDs = {2113},
    TargetNames = {"Rattlecage Skeleton", "Ragged Scavenger", "Mangy Duskbat"},
    MinLevel = 3,
    MaxLevel = 5,
    Range = 80
}