---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Bristleback Battleboar")
AddNameToAvoidWhiteList("Bristleback Quilboar")

StartMobAvoidance()

--- Setting Waypoints ---
local Waypoints = {}
Waypoints[1] = {-2989.614,-810.8782,64.49899}
Waypoints[2] = {-3271.967,-903.9279,61.97006}
Waypoints[3] = {-3126.512,-1078.68,60.12789}

--- Setting Vendor ---
UseDBToRepair(false)
UseDBToSell(true)
local VendorIDs = {}
VendorIDs[1] = 3075

SetQuestRepairVendors(TableToList(VendorIDs))

local TargetNames = {}
TargetNames[1] = "Bristleback Battleboar" 
TargetNames[2] = "Bristleback Quilboar" 


GrindAndGatherPath(TableToStringList(TargetNames),TableToVecList(Waypoints),80)

ZoneProfiles["Mulgore3-8"] = {
    Waypoints = {
        {-2989.614,-810.8782,64.49899},
        {-3271.967,-903.9279,61.97006},
        {-3126.512,-1078.68,60.12789}
    },
    VendorIDs = {3075},
    TargetNames = {"Bristleback Battleboar", "Bristleback Quilboar"},
    MinLevel = 3,
    MaxLevel = 8,
    Range = 80
}