---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Highland Strider")
AddNameToAvoidWhiteList("Young Mesa Buzzard")
AddNameToAvoidWhiteList("Plains Creeper")
StartMobAvoidance()

--- Setting Waypoints ---
local Waypoints = {}
Waypoints[1] = {-1274.57,-3455.48,45.42447}
Waypoints[2] = {-1289.808,-3331.036,41.03161}
Waypoints[3] = {-1088.666,-3336.962,51.77715}
Waypoints[4] = {-1390.38,-3212.517,30.90536}
Waypoints[5] = {-1250.189,-3188.813,39.44151}
Waypoints[6] = {-1033.808,-3653.999,73.59264}
Waypoints[7] = {-967.9659,-3298.443,68.00553}
Waypoints[8] = {-1037.928,-3248.007,45.52531}
Waypoints[9] = {-1040.97,-3384.854,57.18095}
Waypoints[10] = {-960.8683,-3387.813,67.24275}
Waypoints[11] = {-1133.238,-3257.623,45.25296}
Waypoints[12] = {-1108.904,-3352.307,50.55976}


--- Setting Vendor ---
UseDBToRepair(false)
UseDBToSell(true)
local VendorIDs = {}
VendorIDs[1] = 9555

SetQuestRepairVendors(TableToList(VendorIDs))

local TargetNames = {}
TargetNames[1] = "Highland Strider" 
TargetNames[2] = "Young Mesa Buzzard" 
TargetNames[3] = "Plains Creeper" 

GrindAndGatherPath(TableToStringList(TargetNames),TableToVecList(Waypoints),80)

ZoneProfiles["Arathi Highlands30-38"] = {
    Waypoints = {
        {-1274.57,-3455.48,45.42447},
        {-1289.808,-3331.036,41.03161},
        {-1088.666,-3336.962,51.77715},
        {-1390.38,-3212.517,30.90536},
        {-1250.189,-3188.813,39.44151},
        {-1033.808,-3653.999,73.59264},
        {-967.9659,-3298.443,68.00553},
        {-1037.928,-3248.007,45.52531},
        {-1040.97,-3384.854,57.18095},
        {-960.8683,-3387.813,67.24275},
        {-1133.238,-3257.623,45.25296},
        {-1108.904,-3352.307,50.55976}
    },
    VendorIDs = {9555},
    TargetNames = {"Highland Strider", "Young Mesa Buzzard", "Plains Creeper"},
    MinLevel = 30,
    MaxLevel = 38,
    Range = 80
}