---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Dying Kodo")
AddNameToAvoidWhiteList("Ancient Kodo")
AddNameToAvoidWhiteList("Carrion Horror")
StartMobAvoidance()

--- Setting Waypoints ---
local Waypoints = {}
Waypoints[1] = {-1301.2,2039.618,50.62167}
Waypoints[2] = {-1281.236,1921.604,50.9398}
Waypoints[3] = {-1335.425,1799.051,50.39226}

--- Setting Vendor ---
UseDBToRepair(false)
UseDBToSell(true)
local VendorIDs = {}
VendorIDs[1] = 8878

SetQuestRepairVendors(TableToList(VendorIDs))

local TargetNames = {}
TargetNames[1] = "Dying Kodo" 
TargetNames[2] = "Ancient Kodo" 
TargetNames[3] = "Carrion Horror" 

GrindAndGatherPath(TableToStringList(TargetNames),TableToVecList(Waypoints),80)

ZoneProfiles["Desolace35-40"] = {
    Waypoints = {
        {-1301.2,2039.618,50.62167},
        {-1281.236,1921.604,50.9398},
        {-1335.425,1799.051,50.39226}
    },
    VendorIDs = {8878},
    TargetNames = {"Dying Kodo", "Ancient Kodo", "Carrion Horror"},
    MinLevel = 35,
    MaxLevel = 40,
    Range = 80
}
