---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Dustbelcher Wyrmhunter")
AddNameToAvoidWhiteList("Dustbelcher Mauler")
AddNameToAvoidWhiteList("Dustbelcher Shaman")
BlackListSellVendorByName("Yuka Screwspigot");
 BlackListRepairVendorByName("Yuka Screwspigot");
BlackListSellVendorByName("Gruna");
 BlackListRepairVendorByName("Gruna");
StartMobAvoidance()

--- Setting Waypoints ---
local Waypoints = {}
Waypoints[1] = {-7167.332,-2362.888,242.2251}
Waypoints[2] = {-7203.695,-2302.888,245.3519}

--- Setting Vendor ---
UseDBToRepair(false)
UseDBToSell(true)
local VendorIDs = {}
VendorIDs[1] = 1407

SetQuestRepairVendors(TableToList(VendorIDs))

local TargetNames = {}
TargetNames[1] = "Dustbelcher Wyrmhunter" 
TargetNames[2] = "Dustbelcher Mauler" 
TargetNames[3] = "Dustbelcher Shaman" 

GrindAndGatherPath(TableToStringList(TargetNames),TableToVecList(Waypoints),80)

ZoneProfiles["Badlands40-45"] = {
    Waypoints = {
        {-7167.332,-2362.888,242.2251},
        {-7203.695,-2302.888,245.3519}
    },
    VendorIDs = {1407},
    TargetNames = {"Dustbelcher Wyrmhunter", "Dustbelcher Mauler", "Dustbelcher Shaman"},
    MinLevel = 40,
    MaxLevel = 45,
    Range = 80
}