---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Highborne Lichling")
AddNameToAvoidWhiteList("Highborne Apparition")
StartMobAvoidance()

--- Setting Waypoints ---
local Waypoints = {}
Waypoints[1] = {3032.667,-4131.964,103.611}
Waypoints[2] = {2885.193,-3974.406,110.7717}
Waypoints[3] = {2917.516,-4145.279,101.8882}

--- Setting Vendor ---
UseDBToRepair(false)
UseDBToSell(true)
local VendorIDs = {}
VendorIDs[1] = 10361

SetQuestRepairVendors(TableToList(VendorIDs))

local TargetNames = {}
TargetNames[1] = "Highborne Lichling" 
TargetNames[2] = "Highborne Apparition" 

GrindAndGatherPath(TableToStringList(TargetNames),TableToVecList(Waypoints),80)

ZoneProfiles["Azshara46-53"] = {
    Waypoints = {
        {3032.667,-4131.964,103.611},
        {2885.193,-3974.406,110.7717},
        {2917.516,-4145.279,101.8882}
    },
    VendorIDs = {10361},
    TargetNames = {"Highborne Lichling", "Highborne Apparition"},
    MinLevel = 46,
    MaxLevel = 53,
    Range = 80
}