---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Rotting Dead")
AddNameToAvoidWhiteList("Ravaged Corpse")
StartMobAvoidance()

--- Setting Waypoints ---
local Waypoints = {}
Waypoints[1] = {2293.274,674.8899,35.74139}
Waypoints[2] = {2120.546,617.1121,35.51238}

--- Setting Vendor ---
UseDBToRepair(false)
UseDBToSell(true)
local VendorIDs = {}
VendorIDs[1] = 3522

SetQuestRepairVendors(TableToList(VendorIDs))

local TargetNames = {}
TargetNames[1] = "Rotting Dead" 
TargetNames[2] = "Ravaged Corpse" 
 

GrindAndGatherPath(TableToStringList(TargetNames),TableToVecList(Waypoints),80)


ZoneProfiles["Tirisfal5-10"] = {
    Waypoints = {
        {2293.274,674.8899,35.74139},
        {2120.546,617.1121,35.51238}
    },
    VendorIDs = {3522},
    TargetNames = {"Rotting Dead", "Ravaged Corpse"},
    MinLevel = 5,
    MaxLevel = 10
    Range = 80
}