---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Kul Tiras Sailor")
AddNameToAvoidWhiteList("Kul Tiras Marine")
AddNameToAvoidWhiteList("Clattering Scorpid")
StartMobAvoidance()

--- Setting Waypoints ---
local Waypoints = {}
Waypoints[1] = {-508.3306,-4775.701,36.42898}
Waypoints[2] = {-257.3499,-4873.29,29.07109}
Waypoints[3] = {-49.1504,-4877.828,19.47404}
Waypoints[4] = {84.89589,-5023.077,10.49025}
Waypoints[5] = {-194.6051,-5063.928,21.58897}

--- Setting Vendor ---
UseDBToRepair(false)
UseDBToSell(true)
local VendorIDs = {}
VendorIDs[1] = 10369

SetQuestRepairVendors(TableToList(VendorIDs))

local TargetNames = {}
TargetNames[1] = "Kul Tiras Sailor" 
TargetNames[2] = "Kul Tiras Marine" 
TargetNames[3] = "Clattering Scorpid" 

GrindAndGatherPath(TableToStringList(TargetNames),TableToVecList(Waypoints),80)

ZoneProfiles["Durotar5-10"] = {
    Waypoints = {
        {-508.3306,-4775.701,36.42898},
        {-257.3499,-4873.29,29.07109},
        {-49.1504,-4877.828,19.47404},
        {84.89589,-5023.077,10.49025},
        {-194.6051,-5063.928,21.58897}
    },
    VendorIDs = {10369},
    TargetNames = {"Kul Tiras Sailor", "Kul Tiras Marine", "Clattering Scorpid"},
    MinLevel = 5,
    MaxLevel = 10,
    Range = 80
}