---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Spitelash Myrmidon")
AddNameToAvoidWhiteList("Spitelash Siren")
StartMobAvoidance()

---Blacklisted Area---
BlackListPoint(3552.988,-5354.424,196.6631,20)
BlackListPoint(3552.988,-5354.424,196.6631,20)
BlackListPoint(3610.029,-5354.424,172.6983,20)
BlackListPoint(3610.029,-5354.424,172.6983,20)
BlackListPoint(3598.621,-5324.92,172.3981,20)
BlackListPoint(3598.621,-5324.92,172.3981,20)
BlackListPoint(3578.657,-5306.765,172.4191,20)
BlackListPoint(3578.657,-5306.765,172.4191,20)
BlackListPoint(3544.432,-5306.765,185.173,20)
BlackListPoint(3544.432,-5306.765,185.173,20)
BlackListPoint(3518.764,-5327.19,182.1127,20)
BlackListPoint(3518.764,-5327.19,182.1127,20)
BlackListPoint(3501.651,-5349.885,0,20)
BlackListPoint(3501.651,-5349.885,0,20)
BlackListPoint(3530.172,-5368.041,201.4678,20)
BlackListPoint(3530.172,-5368.041,201.4678,20)
BlackListPoint(3504.504,-5379.389,0,20)
BlackListPoint(3504.504,-5379.389,0,20)
BlackListPoint(3507.356,-5397.545,0,20)
BlackListPoint(3507.356,-5397.545,0,20)
BlackListPoint(3555.84,-5399.814,186.3763,20)
BlackListPoint(3555.84,-5399.814,186.3763,20)
BlackListPoint(3530.172,-5408.892,0,20)
BlackListPoint(3530.172,-5408.892,0,20)
BlackListPoint(3590.065,-5402.083,0,20)
BlackListPoint(3590.065,-5402.083,0,20)
BlackListPoint(3601.473,-5381.658,0,20)
BlackListPoint(3601.473,-5381.658,0,20)
BlackListPoint(3570.101,-5370.311,187.0609,20)
BlackListPoint(3570.101,-5370.311,187.0609,20)
BlackListPoint(3587.213,-5338.538,0,20)
BlackListPoint(3587.213,-5338.538,0,20)
BlackListPoint(3555.84,-5331.729,197.4486,20)
BlackListPoint(3555.84,-5331.729,197.4486,20)
BlackListPoint(3558.692,-5286.339,125.1981,20)
BlackListPoint(3558.692,-5286.339,125.1981,20)
--- Setting Waypoints ---
local Waypoints = {}
Waypoints[1] = {3761.188,-5474.708,33.30965}
Waypoints[2] = {3575.805,-5565.488,15.94556}
Waypoints[3] = {3336.233,-5549.601,19.26461}

--- Setting Vendor ---
UseDBToRepair(false)
UseDBToSell(true)
local VendorIDs = {}
VendorIDs[1] = 10361

SetQuestRepairVendors(TableToList(VendorIDs))

local TargetNames = {}
TargetNames[1] = "Spitelash Myrmidon" 
TargetNames[2] = "Spitelash Siren" 

GrindAndGatherPath(TableToStringList(TargetNames),TableToVecList(Waypoints),80)

ZoneProfiles["Azshara52-57"] = {
    Waypoints = {
        {3761.188,-5474.708,33.30965},
        {3575.805,-5565.488,15.94556},
        {3336.233,-5549.601,19.26461}
    },
    VendorIDs = {10361},
    TargetNames = {"Spitelash Myrmidon", "Spitelash Siren"},
    MinLevel = 52,
    MaxLevel = 57,
    Range = 80,
    Blacklists = {
        {3552.988,-5354.424,196.6631,20},
        {3610.029,-5354.424,172.6983,20},
        {3598.621,-5324.92,172.3981,20},
        {3578.657,-5306.765,172.4191,20},
        {3544.432,-5306.765,185.173,20},
        {3518.764,-5327.19,182.1127,20},
        {3501.651,-5349.885,0,20},
        {3530.172,-5368.041,201.4678,20},
        {3504.504,-5379.389,0,20},
        {3507.356,-5397.545,0,20},
        {3555.84,-5399.814,186.3763,20},
        {3530.172,-5408.892,0,20},
        {3590.065,-5402.083,0,20},
        {3601.473,-5381.658,0,20},
        {3570.101,-5370.311,187.0609,20},
        {3587.213,-5338.538,0,20},
        {3555.84,-5331.729,197.4486,20},
        {3558.692,-5286.339,125.1981,20}
    }
}