---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Suffering Highborne")
AddNameToAvoidWhiteList("Anguished Highborne")
StartMobAvoidance()

---Blacklisted Area---
BlackListPoint(6439.585,-4280.666,663.3469,20)
BlackListPoint(6439.585,-4280.666,663.3469,20)
BlackListPoint(6459.711,-4298.443,666.0304,20)
BlackListPoint(6459.711,-4298.443,666.0304,20)
BlackListPoint(6459.711,-4325.11,666.225,20)
BlackListPoint(6459.711,-4325.11,666.225,20)
BlackListPoint(6504.994,-4342.888,0,20)
BlackListPoint(6504.994,-4342.888,0,20)
BlackListPoint(6489.9,-4289.554,664.8922,20)
BlackListPoint(6489.9,-4289.554,664.8922,20)
BlackListPoint(6469.774,-4249.554,0,20)
BlackListPoint(6469.774,-4249.554,0,20)
BlackListPoint(6414.428,-4280.666,0,20)
BlackListPoint(6414.428,-4280.666,0,20)
BlackListPoint(6419.46,-4347.332,668.2085,20)
BlackListPoint(6419.46,-4347.332,668.2085,20)
BlackListPoint(6525.12,-4307.332,668.7535,20)
BlackListPoint(6525.12,-4307.332,668.7535,20)
BlackListPoint(6545.246,-4347.332,682.6563,20)
BlackListPoint(6545.246,-4347.332,682.6563,20)
--- Setting Waypoints ---
local Waypoints = {}
Waypoints[1] = {6615.686,-4058.443,658.4733}
Waypoints[2] = {6409.397,-3947.332,671.3112}
Waypoints[3] = {6525.12,-4093.999,661.6777}

--- Setting Vendor ---
UseDBToRepair(false)
UseDBToSell(true)
local VendorIDs = {}
VendorIDs[1] = 11184

SetQuestRepairVendors(TableToList(VendorIDs))

local TargetNames = {}
TargetNames[1] = "Suffering Highborne" 
TargetNames[2] = "Anguished Highborne" 

GrindAndGatherPath(TableToStringList(TargetNames),TableToVecList(Waypoints),80)

ZoneProfiles["Winterspring55-60"] = {
    Waypoints = {
        {6615.686,-4058.443,658.4733},
        {6409.397,-3947.332,671.3112},
        {6525.12,-4093.999,661.6777}
    },
    VendorIDs = {11184},
    TargetNames = {"Suffering Highborne", "Anguished Highborne"},
    MinLevel = 55,
    MaxLevel = 60,
    Range = 80,
    Blacklists = {
        {6439.585,-4280.666,663.3469,20},
        {6459.711,-4298.443,666.0304,20},
        {6459.711,-4325.11,666.225,20},
        {6504.994,-4342.888,0,20},
        {6489.9,-4289.554,664.8922,20},
        {6469.774,-4249.554,0,20},
        {6414.428,-4280.666,0,20},
        {6419.46,-4347.332,668.2085,20},
        {6525.12,-4307.332,668.7535,20},
        {6545.246,-4347.332,682.6563,20}
    }
}