---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Dust Stormer")


StartMobAvoidance()

---Blacklisted Area---
BlackListPoint(-6712.787,953.138,10.17216,20)
BlackListPoint(-6712.787,953.138,10.17216,20)
BlackListPoint(-6512.787,981.9069,2.349687,20)
BlackListPoint(-6512.787,981.9069,2.349687,20)
BlackListPoint(-6443.089,1121.326,3.635162,20)
BlackListPoint(-6443.089,1121.326,3.635162,20)
BlackListPoint(-6640.059,911.0909,3.829498,20)
BlackListPoint(-6640.059,911.0909,3.829498,20)
BlackListPoint(-6637.029,961.99,0,20)
BlackListPoint(-6637.029,961.99,0,20)
BlackListPoint(-6697.635,877.8959,6.195856,20)
BlackListPoint(-6697.635,877.8959,6.195856,20)
BlackListPoint(-6737.029,886.7479,2.056404,20)
BlackListPoint(-6737.029,886.7479,2.056404,20)
BlackListPoint(-6715.817,1008.463,7.726635,20)
BlackListPoint(-6715.817,1008.463,7.726635,20)
BlackListPoint(-6664.302,1035.019,-2.263137,20)
BlackListPoint(-6664.302,1035.019,-2.263137,20)
BlackListPoint(-6618.847,1048.297,7.91492,20)
BlackListPoint(-6618.847,1048.297,7.91492,20)
BlackListPoint(-6496.263,1079.334,5.901797,20)
BlackListPoint(-6496.263,1079.334,5.901797,20)
BlackListPoint(-6531.483,1026.001,8.640921,20)
BlackListPoint(-6531.483,1026.001,8.640921,20)
BlackListPoint(-6546.577,994.89,3.989879,20)
BlackListPoint(-6546.577,994.89,3.989879,20)
BlackListPoint(-6576.766,941.5567,3.121958,20)
BlackListPoint(-6576.766,941.5567,3.121958,20)
BlackListPoint(-6606.955,892.6678,4.594253,20)
BlackListPoint(-6606.955,892.6678,4.594253,20)
BlackListPoint(-6637.143,857.112,3.695357,20)
BlackListPoint(-6637.143,857.112,3.695357,20)
BlackListPoint(-6702.552,812.6677,0,20)
BlackListPoint(-6702.552,812.6677,0,20)
BlackListPoint(-6571.734,879.3344,12.56056,20)
BlackListPoint(-6571.734,879.3344,12.56056,20)
BlackListPoint(-6496.263,897.1122,7.468079,20)
BlackListPoint(-6496.263,897.1122,7.468079,20)
BlackListPoint(-6606.955,1008.223,6.616498,20)
BlackListPoint(-6606.955,1008.223,6.616498,20)
BlackListPoint(-6541.545,808.2233,4.98351,20)
BlackListPoint(-6541.545,808.2233,4.98351,20)
BlackListPoint(-6571.734,830.4455,10.08491,20)
BlackListPoint(-6571.734,830.4455,10.08491,20)
BlackListPoint(-6516.389,923.7787,0.9049646,20)
BlackListPoint(-6516.389,923.7787,0.9049646,20)
BlackListPoint(-6456.011,977.1122,5.717587,20)
BlackListPoint(-6456.011,977.1122,5.717587,20)
BlackListPoint(-6440.917,914.8899,0,20)
BlackListPoint(-6440.917,914.8899,0,20)
BlackListPoint(-6461.042,1043.779,0,20)
BlackListPoint(-6461.042,1043.779,0,20)
BlackListPoint(-6556.64,1048.223,4.664187,20)
BlackListPoint(-6556.64,1048.223,4.664187,20)
--- Setting Waypoints ---
local Waypoints = {}
Waypoints[1] = {-6309.756,1462.128,7.366013}
Waypoints[2] = {-6430.968,1510.814,6.197518}
Waypoints[3] = {-6558.241,1787.439,5.500055}
Waypoints[4] = {-6603.695,1911.367,7.084071}

--- Setting Vendor ---
UseDBToRepair(false)
UseDBToSell(true)
local VendorIDs = {}
VendorIDs[1] = 15176

SetQuestRepairVendors(TableToList(VendorIDs))

local TargetNames = {}
TargetNames[1] = "Dust Stormer"

  

GrindAndGatherPath(TableToStringList(TargetNames),TableToVecList(Waypoints),80)

ZoneProfiles["Silithus60Elementals"] = {
    Waypoints = {
        {-6309.756,1462.128,7.366013},
        {-6430.968,1510.814,6.197518},
        {-6558.241,1787.439,5.500055},
        {-6603.695,1911.367,7.084071}
    },
    VendorIDs = {15176},
    TargetNames = {"Dust Stormer"},
    MinLevel = 60,
    MaxLevel = 60,
    Range = 80,
    Blacklists = {
        {-6712.787,953.138,10.17216,20},
        {-6512.787,981.9069,2.349687,20},
        {-6443.089,1121.326,3.635162,20},
        {-6640.059,911.0909,3.829498,20},
        {-6637.029,961.99,0,20},
        {-6697.635,877.8959,6.195856,20},
        {-6737.029,886.7479,2.056404,20},
        {-6715.817,1008.463,7.726635,20},
        {-6664.302,1035.019,-2.263137,20},
        {-6618.847,1048.297,7.91492,20},
        {-6496.263,1079.334,5.901797,20},
        {-6531.483,1026.001,8.640921,20},
        {-6546.577,994.89,3.989879,20},
        {-6576.766,941.5567,3.121958,20},
        {-6606.955,892.6678,4.594253,20},
        {-6637.143,857.112,3.695357,20},
        {-6702.552,812.6677,0,20},
        {-6571.734,879.3344,12.56056,20},
        {-6496.263,897.1122,7.468079,20},
        {-6606.955,1008.223,6.616498,20},
        {-6541.545,808.2233,4.98351,20},
        {-6571.734,830.4455,10.08491,20},
        {-6516.389,923.7787,-0,-20},
        {-6456.011,-977,-5,-20},
        {-6440,-914,-0,-20},
        {-6461,-1043,-0,-20},
        {-6556,-1048,-4,-20}
    }
}