---Generated by profile builder---
---Avoidance thread Setup---
AddNameToAvoidWhiteList("Adult Plainstrider")
AddNameToAvoidWhiteList("Prairie Stalker")
AddNameToAvoidWhiteList("Flatland Cougar")
StartMobAvoidance()

--- Setting Waypoints ---
local Waypoints = {}
Waypoints[1] = {-1786.049,-847.1904,26.86629}
Waypoints[2] = {-2319.382,94.65354,43.74842}
Waypoints[3] = {-1714.747,176.3557,11.52163}
Waypoints[4] = {-2182.484,-985.6301,12.48437}

--- Setting Vendor ---
UseDBToRepair(false)
UseDBToSell(true)
local VendorIDs = {}
VendorIDs[1] = 3079

SetQuestRepairVendors(TableToList(VendorIDs))

local TargetNames = {}
TargetNames[1] = "Adult Plainstrider" 
TargetNames[2] = "Prairie Stalker" 
TargetNames[3] = "Flatland Cougar" 

GrindAndGatherPath(TableToStringList(TargetNames),TableToVecList(Waypoints),80)

ZoneProfiles["Mulgore7-13"] = {
    Waypoints = {
        {-1786.049,-847.1904,26.86629},
        {-2319.382,94.65354,43.74842},
        {-1714.747,176.3557,11.52163},
        {-2182.484,-985.6301,12.48437}
    },
    VendorIDs = {3079},
    TargetNames = {"Adult Plainstrider", "Prairie Stalker", "Flatland Cougar"},
    MinLevel = 7,
    MaxLevel = 13,
    Range = 80
}
